### PR TITLE
Indicate current sort criterion for pagination

### PR DESCRIPTION
**Pull request by AndiPersti**
This PR addresses #1991

Add an arrow next to the current sort key in the pagination header which indicates the current sort direction.

### CODE REVIEW

**Comment by AndiPersti** [comment]
Some remarks:

* The design (color, type of arrow, size, ...) is just a suggestion and open to debate. :-)

* On the Users page ("List of all members") the sort keys start with an uppercase letter, on all other pages the sort keys are all lowercase. What style is preferred?

* Should we also indicate the sorting on the search page?:
search
I still don't have a working solution because it's a little bit more complicated on that page without breaking backward compatibility but I think I will get there. :-)

**Comment by agrodet** [comment]
Ha ha, it's funny that I thought about this thing just yesterday! Thanks for taking care of it :) 

Personally, I don't find the arrow very useful. Probably the arrow is used to express "Ascending" and "Descending" but some people won't get that. Also, it is not clear for non-programmers what the ascending order would be for dates. That being said I don't have any better idea at the moment :/ The best option may be to use a different sentence for each option instead of a common icon, but I don't know if it would render nicely. Something like
Word count (Higher first)
Date created (Older first)
Date modified (Most recent first)
Random and Relevance, I dont't know ^^ 

Maybe somebody will get a better idea.

**Comment by AndiPersti** [comment]
Interesting, I thought using arrows for indicating the sort direction is rather common. For example Wikipedia uses it with their tables and probably any GUI file manager when showing the files in list mode. But I admit that the context there is a table with columns while our results are lists.

A similar approach to the one you suggested would be [using a select box](https://ux.stackexchange.com/a/23272). YouTube and I think most online shops use this approach for sorting (and filtering) their search results.

**Comment by agrodet** [comment]
Going with a select box-like thing, I can imagine something like   
Sort by: Date created (Older first)   
centered in the middle, above the pagination line. when clicking on it, the select box would open with the five (for your screenshot) options listed in a way similar to what the post you linked shows.

From the user point of view, we would loose the opportunity to see at a glance all the sorting possibilities. The maximum number of clicks would be equal to what we have now: 2. Overall, I think it would be much clearer than the current version and therefore a better experience. 

I think that not seeing all the sorting possibilities at a glance is something one can get used to.

**Comment by trang** [comment]
For the responsive UI, my plan was to add a "Sort by" button in the toolbar and a menu similar to the "Sort" menu in the GitHub issues.

Quick prototype in the list page of Tatoeba:

Screenshot_2020-02-01 All public lists (2) - Tatoeba(1)


Corresponding code:
```
        <md-toolbar class="md-hue-2">
            <div class="md-toolbar-tools">
                <h2 flex><?= $title ?></h2>

                <md-menu md-offset="5 50" md-position-mode="target-right target">
                    <md-button ng-click="$mdOpenMenu($event)">
                        <md-icon>sort</md-icon> Sort by
                    </md-button>
                    <md-menu-content>
                        <md-menu-item ng-repeat="item in ['list', 2, 22223, 9324, 02934, 12]">
                            <md-button>
                                <md-icon>{{ $index === 1 ? 'check' : 'blank'}}</md-icon>
                                <span style="padding-right: 12px">Option {{item}}</span>
                            </md-button>
                        </md-menu-item>
                    </md-menu-content>
                </md-menu>
            </div>
        </md-toolbar>
```

This implies creating new strings for the sort options, but it can be difficult to find a good word for some cases. As a start, we could consider keeping the current string and add "(ascending)" or "(descending)" in parenthesis next to the option.

For the list, that would look like:
- list name (ascending)
- list name (descending)
- date created (ascending)
- date created (descending)
- number of sentences (ascending)
- number of sentences (descending)
- last updated (ascending)
- last updated (descending)

Also, with this solution, the user won't know right away how a list is sorted, they would have to click on the "Sort by" button and see which option has a check mark next to it.

We could consider:
- Adding the selected value next to "Sort by". But this might take too much space if option has a very long label.
- Adding a `<subheader>` below the toolbar to specify how the items are sorted.

**Comment by AndiPersti** [comment]
> For the responsive UI, my plan was to add a "Sort by" button in the toolbar and a menu similar to the "Sort" menu in the GitHub issues.

Looks good to me. :-)
Will you implement this yourself or do you need some help?
 
> For the list, that would look like:
> 
>     * list name (ascending)
> 
>     * list name (descending)
> 
>     * date created (ascending)
> 
>     * date created (descending)
> 
>     * number of sentences (ascending)
> 
>     * number of sentences (descending)
> 
>     * last updated (ascending)
> 
>     * last updated (descending)

How about 
* List/Tag/User name (A-Z)
* List/Tag/User name (Z-A)
* Newest +
* Oldest +
* Highest number of sentences/words
* Lowest number of sentences/words
* Most recently updated
* Least recently updated
* Most relevant
* Least relevant
* Highest rank *
* Lowest rank *
(* for member status on "List of all members")
(+ for creation dates or "Member since")

I don't think it would be necessary to add "first" after each option, is it? 
Would "(A-Z)"/"(Z-A)" be too Eurocentric?
 
> Also, with this solution, the user won't know right away how a list is sorted, they would have to click on the "Sort by" button and see which option has a check mark next to it.

I personally think the button itself is sufficient but adding a subheader is a good option.

**Comment by agrodet** [comment]
I also think that meaningful words are better than ascendind / descending. Again, ascending date is not very clear.

> Would "(A-Z)"/"(Z-A)" be too Eurocentric?
I think so, yes :D

**Comment by trang** [comment]
> Will you implement this yourself or do you need some help?

Help is always welcome :) You are free to go ahead and rework this PR with the design I suggested, if you wish to. I'm still on the sentence component so you wouldn't be interfering with any un-pushed work that I may have on this area. You are also free to leave it to me if you prefer to dedicate yourself to less frontend'ish tasks.

Either way, I would still like to consult @alanfgh for the wording.

**Comment by alanfgh** [comment]
@trang, is there a change I should look at, or did you want me to comment on the list of options above?

**Comment by trang** [comment]
@alanfgh There is no change to look at yet. We need to figure how to reword the sort options if the sort feature was redesigned as in [my screenshot above](https://github.com/Tatoeba/tatoeba2/pull/2108#issuecomment-581054498). We would need your opinion on the wording suggested so far.

Of course feel free to comment as well on the suggested design itself, in case it doesn't really fulfill your requirements.

I'm listing below the mapping between current string and corresponding new strings. Each sort option would be split into two strings.

https://tatoeba.org/eng/sentences_lists/index
- list name 
  - List name (A-Z)
  - List name (Z-A)
- date created
  - Newest
  - Oldest
- number of sentences
  - Highest number of sentences
  - Lowest number of sentences
- last updated
  - Most recently updated
  - Least recently updated

https://tatoeba.org/eng/sentences_lists/show/9633
- date added to list 
  - Most recently added
  - Least recently added
- date created
  - Newest sentences
  - Oldest sentences

https://tatoeba.org/eng/tags/view_all
- count
  - Highest number of sentences
  - Lowest number of sentences
- name
  - Tag name (A-Z)
  - Tag name (Z-A)

https://tatoeba.org/eng/tags/show_sentences_with_tag/2139
- date created 
  - Newest sentences first
  - Oldest sentences first
- date of tag
  - Most recently tagged
  - Least recently tagged

https://tatoeba.org/eng/users/all
- Username 
  - Username (A-Z)
  - Username (Z-A)
- Member since
  - Newest
  - Oldest
- Member status
  - Highest rank
  - Lowest rank

https://tatoeba.org/eng/sentences/of_user/TRANG
- date modified 
  - Most recently updated
  - Least recently updated
- date created
  - Newest
  - Oldest

https://tatoeba.org/eng/reviews/of/TRANG
- date modified
  - Most recently updated
  - Least recently updated
- date created
  - Newest
  - Oldest
- sentence id
  - Newest sentences
  - Oldest sentences

**Search ("Order" dropdown in sidebar)**
- Relevance
  - Most relevant
  - Least relevant
- Fewest words first
  - Fewest words
  - Most words
- Last created first
  - Newest sentences
  - Oldest sentences
- Last modified first
  - Most recently updated
  - Least recently updated
- Random
  - Random (only case where we don't need to duplicate the strings)

**Comment by agrodet** [comment]
As mentioned above A-Z is not very appropriate. Since there's also a problem of space, I would suggest two things.

1. Every time you used (A-Z), you only repeated the name of the sort option, so I suggest to remove that name (name, username, etc.)
2. Find an appropriate string for the sort order. Alphabetical would be a better but still far from ideal candidate, I think. Actually, what people are the most used to is "computer order". For example, Japanese are used to Latin alphabet coming first and kanjis last. Similarly, I *guess* speakers of other languages are used to the same thing nowadays. I don't know if there is a name for this "computer order", though...

**Comment by alanfgh** [comment]
Several things:

(1) You could use "alphabetical" or "reverse alphabetical" in place of "A-Z" and "Z-A". If I saw one of those, I would assume that it extended beyond A-Z and Z-A to mean what agrodet is calling "computer order". (I believe the technical term for "computer order" is "collation", but I wouldn't suggest using it.)

(2) If you changed, for example, "Newest" to "Newest first", it would be a bit more verbose, but clearer. Otherwise, it could be interpreted as meaning only the newest sentences (down to some cutoff) would be included.

(3) I never was crazy about "Relevance", which (a) has no descriptive power and (b) is inaccurate for those people (for instance, those who like long sentences) for whom it doesn't actually bring up the most relevant sentences. What about either "Closest matches first" or (sacrificing conciseness for explicitness) "Closest matches and fewest words first"? 

(4) Not sure about "Member status: highest rank" and "Member status: lowest rank". This wording might make people feel competitive. We could sidestep this by using "Member status: admin to contributor" or "Member status: contributor to admin".

Otherwise, I think the wording is fine.

**Comment by trang** [comment]
Thanks for your feedback, @alanfgh.

(1) We'll then go with "Alphabetical" and "Reverse alphabetical".

(2) "Newest first" / "Oldest first" is fine. It's still pretty short compared to some of the other strings.

(3) I'm okay with "Closest matches first" instead of "Most relevant" (and I suppose "Closest matches last" instead of "Least relevant").

(4) I was also a bit uncomfortable with "highest rank" / "lowest rank" but had not better idea. "Member status: admin to contributor" seems like a good solution. I suppose we can shorten this a bit with just "Status: admin to contributor".

**Comment by trang** [comment]
As discussed during our weekly call, this would be okay to merge as is, with the initial design proposed (that is, with the arrow next to each sort criterion).

The second design (with the "Sort" button and the options listed in a menu) can be implemented in a couple of months and should be done together with #1063, I think.

**Comment by jiru** [comment]
I’m going to merge this PR because it’s getting old and it already solves the ticket it refers to. Feel free to open a new issue or PR for further enhancements. If not, the new design should make it better at some point.

**Pull request merged**
