### PR TITLE
Editable transcripts

### PR DESCRIPTION
**Pull request by jiru**
Addresses #77.

## How to test it locally
```sh
git checkout editable-transcripts

alias cake='./cake/console/cake -app ./app/' # or something
cake acl create aco controllers Transcriptions
cake acl create aco Transcriptions save
cake acl create aco Transcriptions view
cake acl create aco Transcriptions reset
cake acl grant Group.2 Transcriptions all
cake acl grant Group.3 Transcriptions all
cake acl grant Group.4 Transcriptions all

mysql ... < ./docs/database/updates/2015-05-02.sql # takes about 5h30
mysql ... < ./docs/database/triggers/last_contributions_triggers.sql

cake transcriptions script sentences # takes about 15m
```

## Unsettled questions
* Do we want to keep transcription for Shanghainese (it’s [much failing](https://www.reddit.com/r/shanghainese/comments/2xgb8t/tatoeba_convert_chinese_characters_to/) and using IPA that only a few people can read), [for Georgian](https://tatoeba.org/eng/wall/show_message/21466)?

## Related threads

* [Google group - Editable transcriptions progress](https://groups.google.com/forum/#!msg/tatoebaproject/gauMnAf4G4M/oFVzWxfl4oMJ)
* https://tatoeba.org/eng/wall/show_message/22679
* https://tatoeba.org/eng/wall/show_message/22870
* https://tatoeba.org/eng/wall/show_message/24956
* https://tatoeba.org/eng/wall/show_message/24982

### CODE REVIEW

**Comment by jiru** [comment]
@trang  I consider this ready for production. I posted a [comment on the wall](https://tatoeba.org/jpn/wall/show_message/24982#message_24982) about it. We’ll need to shut down the site for a few hours because of the SQL update script that takes a long time to execute.

**Comment by trang** [comment]
@jiru, alright :) 

Will you have time to take care of the Tatoeba update that includes this feature? If so, when?

Tomorrow is Tatoeba Day, we can get more users to test this.

The next update is scheduled for [December 2nd](https://github.com/Tatoeba/tatoeba2/milestones/2015-12-02).

**Comment by jiru** [comment]
Yes, I can handle inclusion of this during the next update on December 2nd.

If you can, I’d also like to take the time to explain you how it works so that I will not be the only one able to expand or modify that part of the code.

**Comment by jiru** [comment]
You may merge it into dev before the Tatoeba day starts, so that strings may be translated.

**Comment by trang** [comment]
> If you can, I’d also like to take the time to explain you how it works so that I will not be the only one able to expand or modify that part of the code.

Definitely. I will be on IRC tomorrow as usual for Tatoeba Day.

**Pull request merged**
