### PR TITLE
Rename Toki Pona code

### PR DESCRIPTION
**Pull request by jiru**
Solves #2898.

Deployment instructions (as root):

1. Disable reindexation in crontab (both merge and delta update)
    ```
    crontab -e
    ```
2. Make sure latest indexation finished
    ```
    [ -f /tmp/SphinxIndexesShell.php.lock ] && echo "Wait" || echo "Good to go"
    ```
3. Turn on maintenance mode
    ```
    vim /etc/nginx/sites-enabled/tatoeba.org.conf
    systemctl reload nginx
    ```
4. [Deploy](https://github.com/Tatoeba/tatoeba2/wiki/Deployment) (`set-prod-folder.sh` should run the migration script)
5. Generate new Toki Pona indexes
    ```
    cake sphinx_indexes update main tok
    cake sphinx_indexes update delta tok
    ```
6. Turn off maintenance mode
    ```
    vim /etc/nginx/sites-enabled/tatoeba.org.conf
    systemctl reload nginx
    ```
7. Enable reindexation in crontab (both merge and delta update)
    ```
    crontab -e
    ```
8. Cleanup old Toki Pona index files
    ```
    rm /var/manticore/indices/toki_*
    ```

### CODE REVIEW

**Comment by trang** [comment]
Thank you, @jiru 🙂

**Comment by Yorwba** [comment]
Seems like this change [prevented someone from contributing in Toki Pona](https://tatoeba.org/en/wall/show_message/38489) but they were able to fix(?) it by logging out and back in again. Maybe that's the kind of problem fixed by #2901, but I didn't check.

**Comment by trang** [comment]
I didn't check in depth either but yes, it's very likely that there was some issue due to the session holding the old "toki" code and #2901 should solve it.

There's however another scenario which is related to the language detection where the sentence is not saved if the contributor uses "Auto detect" and it's detected as Toki Pona.

And there's a last issue related to the search, where the search doesn't find sentences when searching from English to Toki Pona. I noticed that if I search [sentences in Toki Pona translated into English](https://tatoeba.org/en/sentences/search?from=tok&query=&to=eng), I get 33k+ occurrences. But if I do [the reverse](https://tatoeba.org/en/sentences/search?from=eng&query=&to=tok), I only get ~900 results. 

Maybe this last issue affects more than just Toki Pona because I'm finding inconsistencies for instance with French and Korean:
* [Korean directly translated into French](https://tatoeba.org/en/sentences/search?from=kor&has_audio=&native=&orphans=any&query=&sort=relevance&sort_reverse=&tags=&to=fra&trans_filter=limit&trans_has_audio=&trans_link=direct&trans_orphan=&trans_to=fra&trans_unapproved=&trans_user=&unapproved=any&user=) → 1,550 occurrences
* [French directly translated into Korean](https://tatoeba.org/en/sentences/search?from=fra&has_audio=&native=&orphans=any&query=&sort=relevance&sort_reverse=&tags=&to=kor&trans_filter=limit&trans_has_audio=&trans_link=direct&trans_orphan=&trans_to=kor&trans_unapproved=&trans_user=&unapproved=any&user=) → 1,371 occurrences. Unless I'm missing something, I would have expected it to be 1,550 occurrences.

**Comment by Yorwba** [comment]
> Maybe this last issue affects more than just Toki Pona because I'm finding inconsistencies for instance with French and Korean:
> 
>    * [Korean directly translated into French](https://tatoeba.org/en/sentences/search?from=kor&has_audio=&native=&orphans=any&query=&sort=relevance&sort_reverse=&tags=&to=fra&trans_filter=limit&trans_has_audio=&trans_link=direct&trans_orphan=&trans_to=fra&trans_unapproved=&trans_user=&unapproved=any&user=) → 1,550 occurrences
> 
>    * [French directly translated into Korean](https://tatoeba.org/en/sentences/search?from=fra&has_audio=&native=&orphans=any&query=&sort=relevance&sort_reverse=&tags=&to=kor&trans_filter=limit&trans_has_audio=&trans_link=direct&trans_orphan=&trans_to=kor&trans_unapproved=&trans_user=&unapproved=any&user=) → 1,371 occurrences. Unless I'm missing something, I would have expected it to be 1,550 occurrences.

You're missing that a sentence can have more than one translation in the same language.
```bash
wget 'https://downloads.tatoeba.org/exports/per_language/fra/fra-kor_links.tsv.bz2'
bunzip2 fra-kor_links.tsv.bz2
cut -f1 fra-kor_links.tsv | sort -u | wc -l # 1371
cut -f2 fra-kor_links.tsv | sort -u | wc -l # 1553 # still off by 3, not sure why, maybe some were deleted since Saturday?
```
But the counts for English and Toki Pona are definitely off. I get
```bash
wget 'https://downloads.tatoeba.org/exports/per_language/eng/eng-tok_links.tsv.bz2'
bunzip2 eng-tok_links.tsv.bz2
cut -f1 eng-tok_links.tsv | sort -u | wc -l # 18581
cut -f2 eng-tok_links.tsv | sort -u | wc -l # 18926
```
The count for Toki Pona to English seems [accurate if you limit search results to direct links](https://tatoeba.org/zh-cn/sentences/search?from=tok&has_audio=&native=&orphans=any&query=&sort=relevance&sort_reverse=&tags=&to=eng&trans_filter=limit&trans_has_audio=&trans_link=direct&trans_orphan=&trans_to=eng&trans_unapproved=&trans_user=&unapproved=any&user=), but the number for English to Toki Pona is clearly way too low.

Maybe the link status is also stored in the search index? Then the indices for all languages will have to be rebuilt.

**Comment by trang** [comment]
> You're missing that a sentence can have more than one translation in the same language.

Ah, indeed.

> Maybe the link status is also stored in the search index? Then the indices for all languages will have to be rebuilt.

Gillux explained to me this information is stored in the metadata of the sentence. So basically, we need to reindex all the sentences that are linked to a Toki Pona sentence.

**Pull request merged**
