### PR TITLE
Add language Meitei

### LINKED ISSUE #2520: Meitei (mni)
* Language name: Meitei
* Language info: https://en.wikipedia.org/wiki/Meitei_language
* ISO 639-3 code: MNI
* Public List: https://tatoeba.org/eng/sentences_lists/show/168614
* Icon: https://imgur.com/a/g9FdGR9
* Requested by: https://tatoeba.org/eng/user/profile/m0ya

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR closes #2520.
It adds Meitei (mni).

### CODE REVIEW

**Comment by jiru** [comment]
Looks good. :+1: I just want to point out that the list creator named the list Meeteilon. It looks like there are many names. Do we agree with Meitei?

**Comment by RyckRichards** [comment]
@sabretou agreed on that.

**Comment by sabretou** [comment]
@jiru In the request, the user used the name 'Meitei Language', so we are going with Meitei.

**Comment by jiru** [comment]
Thanks for clarifying. :slightly_smiling_face:

**Pull request merged**
