### PR TITLE
Added language Muskogee (Creek) (mus)

### LINKED ISSUE #2665: Muskogee (Creek) (mus)
* Language name: Muskogee Creek
* Language info: https://en.wikipedia.org/wiki/Muscogee_language
* ISO 639-3 code: MUS
* Public List: https://tatoeba.org/eng/sentences_lists/show/169303
* Icon: https://imgur.com/a/5F6MJ17
* Requested by: https://tatoeba.org/eng/user/profile/eeyinn

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR closes #2665.

It adds Muskogee (Creek) (mus) to Tatoeba.

### CODE REVIEW

**Comment by jiru** [comment]
@RyckRichards The flag file is too big. It weights 5.4KB, and while our "warning limit" is set to 4KB, such a simple flag should be way under 4KB. Could you try to optimize the PNG file before converting it to SVG?

**Comment by RyckRichards** [comment]
I did convert that on https://compresspng.com/. I'll try a different website.

**Comment by RyckRichards** [comment]
@jiru I'v replaced that.

**Comment by jiru** [comment]
Much better, thank you! :+1:

**Pull request merged**
