### PR TITLE
Added language Tigre

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR solves #1815

### CODE REVIEW

**Comment by jiru** [comment]
@RyckRichards thanks! Please remove the PNG file too.

**Comment by RyckRichards** [comment]
@jiru I think I've removed all png files. Did I do that correctly?

**Comment by jiru** [comment]
Yes, thank you. :-)

**Comment by RyckRichards** [comment]
My pleasure, @jiru . Sorry for the inconvenience and my naiveness

**Pull request merged**
