### PR TITLE
Added language Cayuga

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR solves #1734

### CODE REVIEW

**Comment by jiru** [comment]
@RyckRichards thanks! Please also remove the PNG file.

**Comment by RyckRichards** [comment]
Oh... I thought I had removed by deleting the file straight from my fork by pressing delete. Is there a special command for that?

**Comment by jiru** [comment]
Yes, there is a special command for that: `git rm webroot/img/flags/cay.png`

**Comment by trang** [comment]
@RyckRichards Your pull request is currently only adding a new icon. It doesn't have the changes in  `LanugagesLib.php`.

In general, you can double check if your pull request is complete by looking at the "Files changed" tab of the pull request. 

In this case, you can see there is only one file changed:
https://github.com/Tatoeba/tatoeba2/pull/1781/files

If you compare with one of your latest merged pull request, you see there are two files changed:
https://github.com/Tatoeba/tatoeba2/pull/1839/files

**Comment by RyckRichards** [comment]
Oh I'm sorry. I'm going to fix that now :)

**Pull request merged**
