### PR TITLE
Replace CSS property "box-shadow" under language icons with "filter: drop-shadow"

### PR DESCRIPTION
**Pull request by speedysera**
This pull request addresses issue #2046 - use filter: drop-shadow

### CODE REVIEW

**Comment by jiru** [comment]
Hi speedysera! Welcome and thank you for your pull request! :smile:

I had a look at how the flag shadow looked with your PR. If I understand correctly, it makes the shadow fit the actual contour of the flag instead of the square image, right? That is all good, but it seems that your shadow is much bigger than what we currently use:
flags_shadow

If the current shadow is barely perceivable (I have to zoom in to actually see it), yours, in contrast, it a bit too thick in my opinion. Maybe we can find something in between?

**Comment by speedysera** [comment]
Hi jiru! 

   Thanks for the feedback! This time, I've copied the old parameters, please take a look if it's acceptable.

thanks,
speedysera

**Comment by AndiPersti** [comment]
Welcome speedysera!

Just a technical note: For the future I would recommend that you create a separate branch for each PR. Do you know how to do that with git?

**Comment by jiru** [comment]
@speedysera I don’t know why, but it looks like giving the same parameters to `drop-shadow` and `bow-shadow` produce different results (tested on Firefox and Chromium). `drop-shadow` produces a much bigger shadow. It seems that
```css
filter: drop-shadow(1px 1px 3px black);
```
is equivalent (in terms of rendering) to:
```css
drop-shadow(1px 1px 1.33px black)
```

So I suggest that you reduce the blur-radius to 1.33px.

**Comment by speedysera** [comment]
> Just a technical note: For the future I would recommend that you create a separate branch for each PR. Do you know how to do that with git?

Thanks, @AndiPersti! Did you mean something like `git flow feature` or a manual branch creation? I have a chance to try it out to address @jiru 's comment :)

**Comment by AndiPersti** [comment]
It depends on your work style. I'm working on the command line and thus I create branches manually using `git checkout -b <new-branch> dev` (usually after updating the `dev` branch to the current version). But you could also use some plugins or a GUI for creating a new branch.

**Comment by speedysera** [comment]
Thanks @AndiPersti ! Please refer to https://github.com/Tatoeba/tatoeba2/pull/2327 for the new Pull Request

**Pull request closed without merging**
