### PR TITLE
Added language Old French

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR solves #2233 

Language: Old French

### CODE REVIEW

**Comment by jiru** [comment]
I think the we can improve the flag.

First, there is an [SVG version](https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_France_%28XII-XIII%29.svg) that is more lightweight (I highgly suspect the flag on touslesdrapeaux.xyz just copied it from there).

Second, it is originally squared-shaped, but in your 30x20 version, it is horizontally squizzed so the proportions are not respected. However I’m not sure if it’s okay to crop a few lines instead.

For comparison, for the [flag of middle French](https://commons.wikimedia.org/wiki/File:Flag_of_France_(XIV-XVI).svg) (also on [touslesdrapeaux.xyz](https://touslesdrapeaux.xyz/france_renaissance_XIV_XVI.png)). On Tatoeba, it looks like we [simplified it](https://tatoeba.org/img/flags/frm.svg) so it looks more readable at small size.

**Comment by RyckRichards** [comment]
@jiru Thanks a lot. I've fixed this

**Comment by jiru** [comment]
@RyckRichards I don’t see any difference in the new flag. What did change exactly?

**Comment by jiru** [comment]
I tried to rework the flag by removing the first and last line so that it fits the 30x20 proportions.

@RyckRichards Could you ask the language requester (Julien) if this would be okay to represent Old French?

My proposed flag:
fro small

The flag with proportion problems (compare with the [original file](https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_France_%28XII-XIII%29.svg)):
ricardo flag

My proposed flag’s high resolution for reference:
fro

**Comment by RyckRichards** [comment]
Alright, I'm going to ask him.

**Comment by RyckRichards** [comment]
@jiru, he agreed on use this flag

**Comment by RyckRichards** [comment]
@jiru I made all changes needed. Is everything OK now or should I change anything else on my side? Thank you :)

**Comment by jiru** [comment]
It’s okay, thank you!

**Pull request merged**
