### PR TITLE
Added Bulgarian as a User Interface (UI) language

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR enables Bulgarian as a language interface on Tatoeba.
The translator asked me to enable it on dev Tatoeba to make sure how his translations are rendering and make his job easier.
He's aware that Bulgarian will be added on prod once it gets more translations.

### CODE REVIEW

**Comment by jiru** [comment]
Thank you :+1:

**Comment by RyckRichards** [comment]
@jiru I've got the same error at the time I've added #2405 

Instead of https://dev.tatoeba.org/bul, I get https://dev.tatoeba.org/bul/bul/ and therefore, it's displayed:

 
image

**Comment by jiru** [comment]
I just fixed it now.

**Comment by RyckRichards** [comment]
I believe we can add it on prod

image

image

**Comment by RyckRichards** [comment]
I believe they would love to have that on prod since they've been working on that. Here we have the updated status

image

**Comment by trang** [comment]
@RyckRichards The default.pot is still only 40% translated (that's only +2% compared to last time). Was there a specific push from them to have it Bulgarian UI on production already?

We know that it's not a good experience for users to have a UI only half translated so we should perhaps wait until the default.pot is ~80% translated. But if having Bulgarian activated on prod motivates the translators to keep translating, we can of course find a compromise.

**Comment by AndiPersti** [comment]
I agree that a new language should have a higher percentage of `default.pot` translated.
But in addition I think there also should be complete translations of the main pages available, e.g. homepage for guests and members, sentence page, search (result page and advanced search form).

**Pull request merged**
