### PR TITLE
Speedup background jobs startup

### PR DESCRIPTION
**Pull request by jiru**
This is a minor improvement I have been wanting to do for a while. It allows background jobs (currently audio import, list download and language pair export download) to start immediately when the worker is idle, instead of having to wait for up to 10 seconds that the worker pick up the newly-enqueued task. This brings a substantial speedup for the user when the job execution time is nearly instant (e.g. download of a small list, audio import of a few files, or language pair export involving a language with few sentences).

I had to update from CakePHP 3.7 to 3.8 because the dependency dereuromark/cakephp-queue requires it.

:warning: This PR could cause various regressions on Tatoeba because of the CakePHP update. Needs testing.

### CODE REVIEW

**Comment by trang** [comment]
Would it be too ambitious to try and upgrade to 3.10 instead of 3.8 in this PR?

We have this dependency warning: https://github.com/Tatoeba/tatoeba2/security/dependabot/2

**Comment by jiru** [comment]
I’d rather upgrade to 3.10 in a separate PR. Step by step.

**Comment by jiru** [comment]
By the way, if it works, you may not have to refresh the audio import page at all. This happens because the browser is doing a POST-then-GET request. So if the worker have enough time to complete the import before the GET request arrives, you can see the import result right away.

**Comment by trang** [comment]
Thanks for the explanation @jiru! I confirm that I didn't need to refresh the page manually when trying to import audio.

I've tested this out and it all works fine :) 

Just one thing I noticed is that the worker isn't being waken up when [refreshing the list of sentences that can be switched to CC0](https://github.com/Tatoeba/tatoeba2/blob/92ac45e698a3beb146d58a7f921d809d05ac4a61/src/Model/Licensing.php#L36). Was it just forgotten or there was a reason to leave it out?

**Comment by jiru** [comment]
> Just one thing I noticed is that the worker isn't being waken up when [refreshing the list of sentences that can be switched to CC0](https://github.com/Tatoeba/tatoeba2/blob/92ac45e698a3beb146d58a7f921d809d05ac4a61/src/Model/Licensing.php#L36). Was it just forgotten or there was a reason to leave it out?

I forgot about that.

**Pull request merged**
