### PR TITLE
Change handling of hashes and duplicates

### PR DESCRIPTION
**Pull request by AndiPersti**
This PR addresses #1837 and #1647

I've introduced a new `HashTrait` for entities which automatically updates the hash whenever the text or language of a sentence or vocable changes.

The new `DuplicateBehavior` handles the searching for duplicates before saving.

I'll add a Cake Command in a few days which checks/updates all hashes in the database.

### CODE REVIEW

**Comment by AndiPersti** [comment]
Finally I've added a Cake Command for fixing wrong hashes in a table. I've tested it locally and also added some unit tests. I'm not sure about the performance on big tables, but there's a dry-run option so testing on the dev site shouldn't be too inconvenient.

Here's a sample session:

    vagrant@stretch:~/Tatoeba$ cake fix_hashes --help
    Fix wrong hashes in table.
    
    Usage:
    cake fix_hashes [options] <table>
    
    Options:
    
    --batch-size, -b      Number of rows to proceed in one batch.
                          (default: 1000)
    --dry-run, -n         Do everything except saving any changes.
    --hash-column, -c     Name of the hash column. (default:
                          hash)
    --help, -h            Display this help.
    --progress-bar, -p    Show a progress bar.
    --quiet, -q           Enable quiet output.
    --raw, -r             Output changed rows in a machine readable format
                          (id <tab> old hash <tab> new hash)
    --source-columns, -s  Comma separated list of columns the hash is based
                          on. (default: lang,text)
    --verbose, -v         Enable verbose output.
    
    Arguments:
    
    table  Table to fix
    
    vagrant@stretch:~/Tatoeba$ cake fix_hashes sentences
    64 rows checked, no problems found.
    vagrant@stretch:~/Tatoeba$ echo 'update sentences set hash = "abcdef" where id = 4;'|mysql tatoeba
    vagrant@stretch:~/Tatoeba$ echo 'update sentences set hash = "123asd2" where id = 33;'|mysql tatoeba
    vagrant@stretch:~/Tatoeba$ echo 'select id, lang, text, hash, modified from sentences where id in (4,33,58);'|mysql tatoeba
    id      lang    text    hash    modified
    4       deu     Ich bekam keine Gelegenheit, mich dem Mädchen vorzustellen.     abcdef\0\0\0\0\0\0\0\0\0\0      2020-01-18 17:13:13
    33      ber     adsfasdf        123asd2\0\0\0\0\0\0\0\0\0       2020-01-01 19:19:44
    58      eng     foobarbaztest2  1qmbhv\0\0\0\0\0\0\0\0\0\0      2020-01-13 20:17:55
    vagrant@stretch:~/Tatoeba$ cake fix_hashes -n -r sentences
    2/64
    4       abcdef  1ru11pg
    33      123asd2 9gjm5n
    vagrant@stretch:~/Tatoeba$ cake fix_hashes sentences
    64 rows checked, 2 rows changed:
    id 4 - hash changed from "abcdef" to "1ru11pg"
    id 33 - hash changed from "123asd2" to "9gjm5n"
    vagrant@stretch:~/Tatoeba$ echo 'select id, lang, text, hash, modified from sentences where id in (4,33,58);'|mysql tatoeba
    id      lang    text    hash    modified
    4       deu     Ich bekam keine Gelegenheit, mich dem Mädchen vorzustellen.     1ru11pg\0\0\0\0\0\0\0\0\0       2020-01-18 17:13:13
    33      ber     adsfasdf        9gjm5n\0\0\0\0\0\0\0\0\0\0      2020-01-01 19:19:44
    58      eng     foobarbaztest2  1qmbhv\0\0\0\0\0\0\0\0\0\0      2020-01-13 20:17:55

**Comment by trang** [comment]
Took about 5 hours to complete but it went all fine, I think. No noticeable performance impact on the server.

I can't thank you enough for your work :)

**Comment by AndiPersti** [comment]
You're welcome.

Have you logged the output? I would like to know how many sentences had a wrong hash.

**Comment by trang** [comment]
Yes, here it is: [fix_hashes.log](https://github.com/Tatoeba/tatoeba2/files/4121243/fix_hashes.log)

```
8100903 rows checked, 57384 rows changed
```

**Comment by AndiPersti** [comment]
Thanks.

**Comment by Yorwba** [comment]
Do these null bytes at the end of the hash indicate that the actual hash is longer? The visible part seems to be a 7-digit base36 number. If so, that means there's a 50% probability of a hash collision in a set of about 36^(7/2) = 279936 hashes. If that is the full hash, we probably have several collisions already.

**Comment by AndiPersti** [comment]
The hash is stored in the database as a 16 byte binary string (`BINARY(16)`). For hashing we use the 32bit version of [Murmurhash3](https://en.wikipedia.org/wiki/MurmurHash#MurmurHash3) but convert the calculated hash value into a base32 number so we need at most 7 bytes of the available 16 bytes (32^7 > 2^32 > 32^6) and the rest are padding bytes.

Collisions are expected and are handled appropriately:
https://github.com/Tatoeba/tatoeba2/blob/ce583b6ab6cc11f9934444ac92cd702bce2bed75/src/Model/Behavior/DuplicateBehavior.php#L50-L100

**Comment by Yorwba** [comment]
@AndiPersti Thanks for explaining this to me. Good to know that hash collisions are handled correctly.

**Comment by jiru** [comment]
Wow, this is really awesome, @AndiPersti! Thanks a lot for rewriting this part of the code, it’s so much cleaner and reusable now.

**Comment by AndiPersti** [comment]
Thanks. 
It took me some time to get there but I'm also pretty content with it. :-)

**Pull request merged**
