### PR TITLE
Edit in place functionality changed

### PR DESCRIPTION
**Pull request by kwikadi**
Now works on pressing 'edit' button instead of clicking on sentence.
Small CSS changes too.

### CODE REVIEW

**Comment by trang** [comment]
1. When I'm viewing a sentence that has audio, I have an error. The edit button is not displayed.

``
Notice (8): Undefined variable: editImage [APP\views\helpers\menu.php, line 550]
Code | Context
MenuHelper::editButton() - APP\views\helpers\menu.php, line 550
MenuHelper::displayMenu() - APP\views\helpers\menu.php, line 640
SentencesHelper::displayMainSentence() - APP\views\helpers\sentences.php, line 319
SentencesHelper::displaySentencesGroup() - APP\views\helpers\sentences.php, line 94
include - APP\views\sentences\show.ctp, line 162
View::_render() - CORE\cake\libs\view\view.php, line 736
View::render() - CORE\cake\libs\view\view.php, line 431
Controller::render() - CORE\cake\libs\controller\controller.php, line 909
Dispatcher::_invoke() - CORE\cake\dispatcher.php, line 207
Dispatcher::dispatch() - CORE\cake\dispatcher.php, line 171
[main] - APP\webroot\index.php, line 86
``

2. The edit button needs to have the "hand" cursor on rollover. To make it clear it's a button.

3. Not a priority. It would be nice to unify the graphical look of the buttons: http://prntscr.com/665nvw.
* green background for "OK" 
* white background for "cancel"
* [ cancel ] [ ok ], rather than [ ok ] [ cancel ]

**Comment by kwikadi** [comment]
The 2010 database does not seem to have any sentences with associated audio, so I can't be sure, but I have fixed what seems to be the problem. I have also added the hand cursor, and styled the buttons to your preference.

**Comment by trang** [comment]
@kwikadi you can log in as an admin. You will see on the sentence's page, on the side, a little form to turn on/off the audio http://prntscr.com/666tvw. Just use this for your tests.

**Comment by kwikadi** [comment]
Found it, thanks!

http://i.imgur.com/J7FamTa.png

**Pull request merged**
