### PR TITLE
Updated Middle English flag

### PR DESCRIPTION
**Pull request by jeanm**
This PR addresses issue #1821.

### CODE REVIEW

**Comment by trang** [comment]
Thank you for your pull requests @jeanm. We are however not going to merge them as is. We currently have an incoming pull request that migrates our language icons to SVG (#1806).

You will either have to update your pull requests once #1806 is merged, or you can simply close this pull request and let @RyckRichards handle it instead.

**Comment by jeanm** [comment]
Sure! I had seen the SVG PR but hadn't realised it was likely to be merged soon. Happy to rebase on top of it once it's ready.

**Comment by jeanm** [comment]
I’m unfortunately going to be a little busy for the next few weeks, so if somebody is able to take over (@RyckRichards or someone else) that’d be great. I’ll be closing this PR and the related #1826. Thanks for all your work!

**Comment by trang** [comment]
No problem @jeanm. We usually don't expect our users to make pull requests anyway. @RyckRichards is in charge of that :)

**Pull request closed without merging**
