### PR TITLE
Added Jewish Babylonian Aramaic

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR solves #2183

### CODE REVIEW

**Comment by trang** [comment]
@RyckRichards, the language icon's size is too big. Perhaps you have not resized the PNG to be 30x20 pixels before you turned it into SVG?

**Comment by RyckRichards** [comment]
@trang I'm really sorry. I'm going to fix this.

**Comment by RyckRichards** [comment]
@trang Fixed! Hope it's good enough :)

**Comment by trang** [comment]
No problem @RyckRichards. It is fine now. As you can see, the status is green.

When you see that your commit has a red cross next to it, you can click on the cross, then on the "Details" link. Then it should tell you some information about what's wrong.

**Comment by jiru** [comment]
It looks like the flag [consisted of some written text](https://imgur.com/n653OTw), but now it has been downsized to 30x20, it’s completely unreadable. I don’t think this is a good flag to represent the language.

**Comment by RyckRichards** [comment]
@jiru - I've asked about a new flag suggestion

**Comment by conlangbecca** [comment]
Maybe this would work better? https://imgur.com/a/YAzMdxi

**Comment by jiru** [comment]
Thank you @conlangbecca! I can’t say about the meaning of the text, but it certainly looks better yes. :smiley_cat:
@RyckRichards I think we can use this new flag.

**Comment by RyckRichards** [comment]
Alright!

**Comment by RyckRichards** [comment]
@jiru done

**Pull request merged**
