### PR TITLE
Replaced flag for Tigrinya

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR addresses #312 

@Kobi Kai [related](https://github.com/Tatoeba/tatoeba2/issues/312#issuecomment-907747821) that there are more native Tigrinya speakers in Tigray than in Ethiopia.

### CODE REVIEW

**Comment by oyd11** [comment]
I'm afraid completely changing it from Eritrea to Tigray, could even be offensive for many Eritreans... I think this isn't a good idea, please re-read my original thread about it.

**Comment by trang** [comment]
@RyckRichards Before updating the pull request, can you try to get in touch with the [native speakers of Tigrinya](https://tatoeba.org/en/users/for_language/tir) to confirm that they are fine with changing the flag to https://commons.wikimedia.org/wiki/File:Flag_of_Tigrinya_language_(ET-ER).png?

**Comment by RyckRichards** [comment]
@trang Sure
@oyd11 Going to read it now.

**Comment by yosiasz** [comment]
Replace flag for Tigrinya? That is like saying replace flag for Russian, a language spoken both in the country of Russsia and Ukriane. Tigrinya is a language spoken in 2 different countries (Eritrea and Northern region of Ethiopia Tigray) though spoken with some slight regional differences.

**Review by yosiasz — CHANGES_REQUESTED** [review]
Tigrinya is a language not a country

**Comment by oyd11** [comment]
@yosiasz, so what's actually your suggestion? you seem to dislike something with PR, but I'm not sure what:

1. Semantics: Change the PR title - we're obviously not changing the "Flag of Tigrinya" we're changing "the Icon for Tigrinya on Tatoeba" (in analogy of "we're not changing the 'flag of Russian'")
2. Choose a different flag to represent the Tigrinya language (which one do you suggest, and why? The Eritrean, the Tigray, Ethiopian, or other?)
3. Start a discussion about disconnecting languages from Flags on Tatoeba in general (probably elsewhere)
4. Replace the Flag representing the Russian language with a flag of Russia-and-Ukraine (plus Belarus, Kazakhstan and Kyrgyzstan), or with some historical flag of Russia?

**Pull request merged**
