### PR TITLE
Add Serbian as UI

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR adds Serbian (ISO 639-3 [српски]) as User Interface.
Lazar has been doing a great job and keeps translating every day.

### CODE REVIEW

**Comment by jiru** [comment]
As much as I’d like to make Serbian available, I don’t think it’s ready yet:
image

That said, we can still merge your PR without enabling Serbian. This way, we’ll have the configuration ready for when the Serbian translation will be complete enough.

**Comment by trang** [comment]
It's definitely not ready for prod but I think the main goal here is to enable it on the dev website, so that the translators can get to see the result of their translations.

**Comment by RyckRichards** [comment]
That too. Also, I think people will notice that there's a "Serbian UI" already but it's not fully translated and so, they might get motivated to start helping us.

**Comment by jiru** [comment]
Thank you, @RyckRichards :smile:

**Comment by jiru** [comment]
Serbian is now available on tatoeba.org as a UI language.

**Comment by RyckRichards** [comment]
Thank you!!!!! More languages are coming :)

**Pull request merged**
