### PR TITLE
Got rid of inclusion of .js files in AJAX response for rerunning them

### PR DESCRIPTION
**Pull request by ventice**
This PR addresses issue #1151 
Here is what's done:
1. `watch.js` is developed. This is a small jQuery plug-in holding registry of rules that are to be ensured for the entire document. There are two families of actions in it: **registration** and **DOM modification**. The rules are registered on the startup by all the pages that run jQuery and are immediately applied to the scope in which they are called. After that the rule (a JS function doing jQuery calls) is stored in a list and all the rules are applied to the element being added to DOM by the second family of functions. See image for more details.
watch_js_workflow
2. The JS files related to this issue are changed to use `watch.js`. This effectively means putting all the code inside `$(document).ready(...)` callback into a new function which is registered with `watch.js`. Additionally, all the global calls to `$(...)` are replaced to calls with context to operate only under the node whose DOM has been modified. Note that initially I planned to operate on the node being added (before attaching to DOM) but it may result to error for queries using `parent()` calls for localizing siblings.
3. `watch.js` is shipped by default before other scripts are loaded.
4. `transcriptions.js` is added to be available without being embedded via AJAX call.
5. All the scripts initially shipped with AJAX response are removed.

### CODE REVIEW

**Comment by ventice** [comment]
Please note that if you prefer to keep the initial hack with running JS by embedding it in HTML to avoid introduction of such "frameworks", I can fix the issue by simply adding `transcription.js` to default set of scripts. In this case it isn't downloaded upon receiving the response, so the warning described in the issue isn't written.
What are the drawbacks of keeping the "hack". Since the code inside `$(document).ready` is unexpectedly run multiple times, it may result in registration of the same handler as many times, as many responses are received which may result in bugs like double sentences. So, the code inside `$(document).ready` should make sure it is idempotent (running it multiple times make the same result is running it once), for instance by removing any handlers before registering them.
This code partially mimics AngularJS's approach to watching variables, so, if you are planning to migrate to AngularJS, we can live without my reinvented wheel.

**Comment by trang** [comment]
Thank you very much for the explanations :)

I do have plans to migrate to AngularJS, but at this stage I have no certainty that the plans won't be dropped for whatever reason, and I have no clear idea of how long it will take. So I see no problem in using your reinvented wheel in the meantime :p

To ensure that I understand properly, let's say I want to fix the synchronous XMLHttpRequest warning for `/sentences/add`, I would have to:

1. Remove the Javascript from [sentences/add_an_other_sentence.ctp](https://github.com/Tatoeba/tatoeba2/blob/dev/app/views/sentences/add_an_other_sentence.ctp#L42).
2. Inject these scripts from [sentences/add.ctp](https://github.com/Tatoeba/tatoeba2/blob/dev/app/views/sentences/add.ctp) instead.
3. Use `$(document).watch("addrule", ...)` for each of the [scripts involved](https://github.com/Tatoeba/tatoeba2/blob/dev/app/views/helpers/sentences.php#L754).
4. Use `.watch("prepend", data);` instead of `.prepend(data);` in [sentences.contribute.js](https://github.com/Tatoeba/tatoeba2/blob/dev/app/webroot/js/sentences.contribute.js#L56).

Right?

If that's correct I can merge your pull request. 

I can also wait if you'd like to also take care of the warnings on `sentences/add` and `sentences_lists/show/{listId}` (there might be other places, but those are the 2 main ones).

**Comment by ventice** [comment]
> let's say I want to fix the synchronous XMLHttpRequest warning for /sentences/add
To tell the truth in this refactoring the warning itself is very secondary issue. The warning occurs when a **new** script is returned from AJAX request and inserted into the document, so, since browser cannot render the added content before the script is downloaded (because the script may do some tweaking of the document which in our case it really does). This downloading of requested script is where the warning comes from since the downloading may take a while blocking the browser. So, if our sole goal is to get rid of the warning (and its symptoms), we have to make sure that no **new** scripts are returned from AJAX requests. This can be easily achieved by moving all such scripts to default set of scripts loaded with every page. In this case we won't have any warning even though the trick of running JavaScript inside `$(document).ready` by multiple insertion of scripts into the document will still be present.
Anyhow, such trick has potential problems with the maintainability of the code. When writing code any future tatoeba developer may rely on the fact that code inside `$(document).ready` handler should run only once. So, this code may be made non-idempotent (idempotent behavior is the one when multiple invocations have the same effect as single invocation) which may cause bugs. An example of bug is the one with multiple translations of the same sentence. The handler of click of 'translate" button wasn't idempotent, so clicking it multiple times resulted in registration of many handlers. Same kind of bugs are potentially hidden in code in which handlers are misused or used in non-traditional way. My fix tried to address this issue by moving the code from ready-handler to rule. I also tried to avoid processing of entire document at every modification but I failed to completely isolate the scope of the rule, because some rules require logic that only works in the context of the document (navigating by 'parent()'). There are also cases when insertion of rules by processing the entire would work (for instance, rules referring to `body`) and my "fix" would not. Currently it works because our rules don't do global queries but if you are ever planning to run such queries (namely: after completing AJAX request, change something in the header), this new infrastructure would be an obstacle for this.

So, if you still welcome such changes provided the restrictions, I can also fix the cases you mentioned, if not, I can discard it and simply get rid of the warnings in the minimal possible way (that fix will affect 10 lines of code at most).

**Comment by ventice** [comment]
On the other hand, I can still keep the "watching" approach but run the rules not over modified piece of code, but over entire document. It will eliminate restrictions posed over scripts and still be better than multiple invocations of `$(document).ready`

**Comment by trang** [comment]
> An example of bug is the one with multiple translations of the same sentence. The handler of click of 'translate" button wasn't idempotent, so clicking it multiple times resulted in registration of many handlers. Same kind of bugs are potentially hidden in code in which handlers are misused or used in non-traditional way.

Possibly these issues are related to what you're saying there:
* https://github.com/Tatoeba/tatoeba2/issues/566
* https://github.com/Tatoeba/tatoeba2/issues/692


> On the other hand, I can still keep the "watching" approach but run the rules not over modified piece of code, but over entire document. It will eliminate restrictions posed over scripts and still be better than multiple invocations of $(document).ready

Alright so in the end it's up to you :) 

Would you rather do minimal changes, because there are plans to migrate to AngularJS and you'd rather spend time on other issues? Or would you rather do the refactoring because it makes the code more robust and makes you sleep better at night, even if your framework will be in use only for a "short" time?

I'm personally fine either way so you should do what feels more fulfilling for you.

**Comment by ventice** [comment]
Ok, I will keep watch.js (it's very tiny framework so we can happily drop without remorse when we move to AngularJS) but make the scope of queries the entire document. I will also check the issues you have cited.

**Pull request closed without merging**
