### PR TITLE
repair cs locale

### PR DESCRIPTION
**Pull request by zen0bit**
repair cs locale

default.po leaking `&nbsp;`

### CODE REVIEW

**Comment by Yorwba** [comment]
@zen0bit Thank you for trying to help improve the Czech locale. However, the .po files you're modifying are not the source of truth for this; you'll need to correct the strings on Transifex instead. See the [description on the wiki](https://en.wiki.tatoeba.org/articles/show/interface-translation#).

**Comment by zen0bit** [comment]
Link on wiki is wrong!

[proper one](https://explore.transifex.com/tatoeba/tatoeba_website/)

**Comment by zen0bit** [comment]
Link on wiki is wrong!

[proper one](https://explore.transifex.com/tatoeba/tatoeba_website/)

I requested access there.

Waiting...

**Comment by jiru** [comment]
@zen0bit Thanks for reporting the broken links! I fixed them.

**Pull request closed without merging**
