### PR TITLE
Added language Lezgi

### LINKED ISSUE #2653: Lezgi
* Language name: Lezgi
* Language info: In 2002, Lezgian was spoken by about 397,000 people in Russia, mainly Southern Dagestan, and in 1999 by 178,400 people in mainly the Qusar, Quba, Qabala, Oghuz, Ismailli and Khachmaz (Xaçmaz) provinces of northeastern Azerbaijan. Lezgian is also spoken in Kazakhstan, Kyrgyzstan, Turkey, Turkmenistan, Ukraine, Germany and Uzbekistan by immigrants from Azerbaijan and Dagestan. Some speakers are in the Balikesir, Yalova, Izmir, Bursa regions of Turkey especially in Kirne (Ortaca), a village in Balikesir Province which touches the western coast, being south-west of Istanbul. The total number of speakers is about 800,000.
* ISO 639-3 code: lez
* Public List: https://tatoeba.org/eng/sentences_lists/show/169305
* Icon: 
image

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR closes #2653.
It adds Lezgi to Tatoeba.

### CODE REVIEW

**Comment by jiru** [comment]
You named the language *Lezli*. Isn’t it supposed to be *Lezgi*?

The flag looks very blurry. Isn’t there a way to make the horizontal white bars and the inscription a bit more visible?

**Comment by RyckRichards** [comment]
Oh, sorry about that.

**Comment by jiru** [comment]
Thank you for fixing the language name :+1:

I will wait for your input about the blurriness.

**Comment by jiru** [comment]
Thank you, @RyckRichards! I merged the PR and fixed (well, improved a bit) the blurriness in a later commit.

**Comment by jiru** [comment]
@RyckRichards I merged this PR already but all the sentences in the Lezgi list are red. If I don’t do anything else, Lezgi will land on tatoeba.org with the next update but with red sentences only. Shall I revert adding this language before the next update?

**Comment by RyckRichards** [comment]
I don't think so. We'd have to revert the addition of some other languages,
too.

@sabretou ***@***.***> what do you think?

>

**Comment by sabretou** [comment]
@RyckRichards I think the languages that have been added should remain. We'd only have to re-add them in the future if they are requested again.

The only issue, I think, would be if a user found that there are no valid sentences for that language, but I don't think that will be a major issue.

**Comment by RyckRichards** [comment]
Agreed!

**Comment by jiru** [comment]
Thank you for your answer. In this case Lezgi will be included in the next update.

**Pull request merged**
