### PR TITLE
CakePHP 2.9.4

### PR DESCRIPTION
**Pull request by halfdan**
This PR upgrades Tatoeba to the latest CakePHP 2.x version.

**NOTES: ** 
- Highly experimental. Not yet tested at all. Still has bugs.
- nginx.conf needs a change to work with the new CakePHP version
- more to be documented

### CODE REVIEW

**Comment by halfdan** [comment]
Known Issues:

- Viewing sentences is broken
- Registration screen does not work
- There seems to be an issue with authorization when submitting forms

18 hours is enough for today - continuing tomorrow.

**Comment by halfdan** [comment]
A couple things here:

- This now fixes #1279 and properly initializes the remember me feature.
- The remember me cookie is now encrypted since we don't want to store user/pass in plain text on the client side
- We update angular to the latest 1.x and angular-material to its latest version.

**Comment by trang** [comment]
Alright, time to merge this. It's stable enough :) I'll be fixing whatever is left to fix on the dev branch.

There are a couple of things that have been left out intentionally:
- the mass import of sentences doesn't work at all
- some of the tools are not working

These will not be fixed for the incoming Tatoeba update. I'll create issues for these topics later on.

Just for the reference, this PR addresses #1122.

**Comment by jiru** [comment]
Good job! :-)

**Pull request merged**
