### PR TITLE
Add links to Tatominer

### PR DESCRIPTION
**Pull request by trang**
Wall thread: https://tatoeba.org/en/wall/show_message/37536

### CODE REVIEW

**Comment by RyckRichards** [comment]
@trang Perhaps it would be good to prefill the [Add sentence page](https://tatoeba.org/en/sentences/add) with the word we've clicked on Tatominer. Otherwise, it's easy to forget the word we're working on.

**Comment by trang** [comment]
@RyckRichards I'm not entirely convinced it would help. I guess if you just look at the word and click on it without really thinking, then it's easy to forget. But I would imagine that you don't mindlessly click on a word. You would first try to come up with a sentence and only once you have an idea of the sentence you want to write, you could click on the word. In which case, normally, it shouldn't be that easy to forget about the word...

Perhaps it can help in the sense that you would have less characters to type if the word is already prefilled, but I feel it could also be an annoyance because you have to spend some time to move the cursor around the word.

**Comment by RyckRichards** [comment]
I have thought on something like that:

1st - user click on the word "chuchu" in "https://tatominer.netlify.app/por.html". It'll open https://tatoeba.org/en/sentences/add#chuchu

2nd - that page would display something like this

**Comment by trang** [comment]
I see. I would suggest that you open a separate ticket for this @RyckRichards :) It's not a bad idea, just not something that I think is high prio, so it doesn't have to be solved in the scope of this PR.

**Comment by RyckRichards** [comment]
Sure, thank you!

**Pull request merged**
