### PR TITLE
Replaced flags

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR addresses #2292 

Related Wall post: https://tatoeba.org/eng/wall/show_message/34867 (By sabretou)
Solloliloquist also suggest changing otk (Old Turkic) flag 

He suggested improvements for the following flags:

Gulf Arabic (afb)
Arabic (ara)
Cayuga (cay)
Lower Sorbian (dsb)
Dutton World Speedwords (dws)
Scots (sco)
Scottish Gaelic (gla)
Kamba (kam)
Naga (Tangshang) (nst)
Old Spanish (osp)
Sanskrit (san)
Tahaggart Tamahaq (thv)
Old Turkic (otk)
Gallery: https://imgur.com/a/zV2MnQ

### CODE REVIEW

**Comment by jiru** [comment]
@RyckRichards Thanks! You mentioned changing the flags for the following languages but didn’t change the image:
*  Arabic (ara)
*  Lower Sorbian (dsp)
* Dutton World Speedwords (dws)
* Old Spanish (osp)
* Sanskrit (san)
* Tahaggart Tamahaq (thv)

Also, the imgur link doesn’t work.

**Comment by RyckRichards** [comment]
Thanks for letting me know, @jiru ! I'm glad I made a backup. I'm going to upload on Imgur and update these flags :)

**Comment by RyckRichards** [comment]
This is the link for the missing flags: https://imgur.com/a/3rK3eEt
```ara, dsb, dws, osp, san, thv```

**Comment by RyckRichards** [comment]
@jiru, I hope I've fixed everything now :)

**Comment by jiru** [comment]
@RyckRichards Yes, it’s all good! I just deployed the new flags on tatoeba.org.

**Pull request merged**
