### PR TITLE
Add additional check for duplicate sentences.

### PR DESCRIPTION
**Pull request by zachleigh**
This pull request address issue #1336.   

I added checks for both the text and language of the new sentence. If these two conditions are met, it will be marked as a true duplicate.

### CODE REVIEW

**Comment by ckjpn** [comment]
I don't know if this should be added as a new issue, but I wonder how duplicates of "orphan" sentences are being handled.

1.
Ideally, if a member contributes a duplicate of an existing sentence without an owner, the person contributing the duplicate should automatically become the owner of the existing sentence.

2.
Another option would be to automatically delete the old sentence and link all the translations to the newly-contributed sentence, sort of like what the duplicate-merging script does.

Personally, I think suggestion 1 is probably better.  However, I can understand why others might prefer suggestion 2.

**Comment by trang** [comment]
@zachleigh, one more thing to fix.

[Odexed reported an issue](https://tatoeba.org/eng/wall/index#message_27452) with the sentence `Постарайся успокоиться.`.

I tried to add this sentence several times on the dev website (this change is deployed on the dev website), and strangely it was not detected as a duplicate.

While debugging locally `_confirmDuplicate()`, after I added several times the sentence `Постарайся успокоиться.`, I found out that:

* $text: `Постарайся успокоиться.`
* $lang: `rus`
* $sentence:
```
Array
(
    [Sentence] => Array
        (
            [id] => 540152
            [lang] => epo
            [text] => Ŝia deziro iĝi kuracistino spronis ŝin.
            [correctness] => 0
            [user_id] => 3138
            [created] => 2010-09-30 18:35:48
            [modified] => 2010-09-30 18:35:48
            [dico_id] => 
            [hasaudio] => no
            [script] => 
            [hash] => 3ms1niv
        )

)
```

Since several senences can have the same hash. We have to retrieve all the sentences with the corresponding hash and loop through these sentences.

**Comment by trang** [comment]
@ckjpn 

> I don't know if this should be added as a new issue, but I wonder how duplicates of "orphan" sentences are being handled.

This is another issue.

**Comment by zachleigh** [comment]
@trang Ill finish this one up tomorrow.

**Comment by zachleigh** [comment]
@trang It now gets all sentences that match the hash and loops through them looking for a exact match.

**Pull request merged**
