### PR TITLE
Redesign sentence comments

### PR DESCRIPTION
**Pull request by trang**
This issue is part of #1180. This is a redesign of the sentence comments. It is ready to handled RTL (#74).

* The new comments design is based on the [Card component](https://material.google.com/components/cards.html) of Material Design, with simply a header and a body (no rich media).
* On pages where the sentence is displayed, the sentence is now outside of the comment block. It is displayed with a grey background to make it easier to distinguish from the comment. 
* The language icon for the sentence is displayed on the end side of the sentence (right side on LTR and, left on RTL interface). This copies the layout of the contribution logs. I'm still not completely decided on putting the language icon on the end side, but I'd like to give it a try.
* The sentence menu is using icons instead of text:
  * `visibility_off` icon => hidden
  * `delete` icon => delete
  * `edit` icon => edit
  * `reply` icon => # (used on pages other than the sentence's page)
  * `link` icon => # (used for non-authenticated users or on the sentence's page)
* The menu icons are placed in the header, rather than at the bottom of the body in order to keep these options around the same area as they used to be. Later on we might consider using a [menu](https://material.google.com/components/menus.html) instead of displaying the icons straight away.
* The avatars border-radius has been reduced to look like a rounded square instead of a circle, to avoid having a too huge shape inconsistency accross the website.
* The username of the sentence owner has been removed because I don't think it is necessary. It was introduced upon [a request](https://app.assembla.com/spaces/tatoeba2/tickets/292-sentence-owner--39-s-name-in-comments/details) from a user who wanted to see the username to be able to notice when a comment is posted on his sentences. This use case was actually not too relevant back then, but it is even less relevant today. There's much more activity on the website, which makes it unlikely that a user would notice from the homepage a comment on their sentence unless they are looking at the page 24/7. Also, users have a page that lists all the comments on their sentences. Having the username of the owner doesn't bring much value.

**Old comments**

screenshot_57

screenshot_60

**New comments**

screenshot_58

screenshot_59

### CODE REVIEW

**Comment by ckjpn** [comment]
Here are several suggestions and ideas to consider.

* I'd suggest moving the flag and link icon to the top, rather than vertically centering it. (in the logs, too)
* I'd also suggest using a "link" icon instead of an "info" icon.
* Possibly consider putting the username and avatar of the member making to comment at the top.
* Consider removing the gray background behind the sentence, or at least making it a lighter color to improve readability with higher contrast.
* I still think having the link and the language flag to the (upper) left of the sentence would be a good idea.  Maybe it's just because that's what I'm used to on the website, but I have the gut-feeling that it's also the more intuitive place to have such items and that's what the average visitor will expect.


screen shot 2016-09-11 at 00 34 19

**Comment by ckjpn** [comment]
These screenshots are of the contributions logs, but show how sentences would also look in the comments if the flag and link icon are moved up to the top, instead of being vertically centered.  I think it would be a good idea to do so for both.  (Please just ignore all the other changes, which I know you are not likely to like.)

## Without my Stylish CSS changes.
without

## With my Stylish CSS changes.
with

**Comment by trang** [comment]
> I'd suggest moving the flag and link icon to the top, rather than vertically centering it. (in the logs, too)

I agree with having the language and info icon aligned at the top, but it's difficult to position properly. Considering there are very few sentences that are that long, I don't consider it a high priority that needs to be fixed now.

> I'd also suggest using a "link" icon instead of an "info" icon.

I'm not convinced the link icon will be intuitive enough. The info icon is a more common icon and users I think it makes it easier for user to understand that when they click the icon, they get more information about the related sentence.

> Possibly consider putting the username and avatar of the member making to comment at the top.

I feel it makes more sense if the sentence is above. Otherwise it gives the impression that the author of the comment is also the author of the sentence.

> Consider removing the gray background behind the sentence, or at least making it a lighter color to improve readability with higher contrast.

I'm not sure if readability is really an issue here. The grey background is relatively light. In general I try not to use background colors, but here I feel it was necessary to make a clear separation between the comment and the sentence.

**Comment by ckjpn** [comment]
>I agree with having the language and info icon aligned at the top, but it's difficult to position properly. Considering there are very few sentences that are that long, I don't consider it a high priority that needs to be fixed now.

I think it's this CSS.

```
#logs > md-list-item > div.md-list-item-text.layout-column{margin:0px ! important}
#logs > md-list-item{border:1px solid blue;margin:0px ! important;min-height: 10px;}
#logs > md-list-item div._md-secondary-container{margin:0px ! important;}
```
If that doesn't do it, it is something else in this.  Click the "see CSS" link.

https://userstyles.org/styles/132392/tatoeba-org-make-logs-so-less-scrolling-is-needed

**Comment by trang** [comment]
@ckjpn, the CSS you provided breaks the vertical alignment of the content.

**current alignment**

screenshot_62

**with your CSS**

screenshot_61

**Comment by ckjpn** [comment]
Maybe it was this part of the CSS that moved the flag to the top.
```
.md-2-line{margin-top:15px;}
.md-2-line .content{padding-top:-30px ! important}
```

Here is the complete CSS for https://userstyles.org/styles/132392/tatoeba-org-make-logs-so-less-scrolling-is-needed.

```
.md-2-line{margin-top:15px;}
.md-2-line .content{padding-top:-30px ! important}
.md-2-line p{font-size:.4em ! important;color:#bbb;}
.md-2-line p a{font-size:2em;color:blue}
.md-icon-button{background-color:#eef;border:1px solid #aaa}
.md-icon{background-color:blue}

#logs > md-list-item > div.md-list-item-text.layout-column{margin:0px ! important}
#logs > md-list-item{border:1px solid blue;margin:0px ! important;min-height: 10px;}
#logs > md-list-item div._md-secondary-container{margin:0px ! important;}


/* Add background colors back into the logs */

.sentence-update{background: #ffffe7 !important;}
.sentence-obsolete{background: #eee !important;}
.sentence-insert{background: #e7ffe7 !important;}
.sentence-insert{background: #e7ffe7 !important;}
.sentence-delete{background: #fcc !important;}

.link-insert{background:#dff}
.link-delete{background:#ffedcc}

/* Remove the Avatar from the logs */

.md-avatar{
display:none ! important}
}
```

**Comment by ckjpn** [comment]
>Possibly consider putting the username and avatar of the member making to comment at the top.
>>I feel it makes more sense if the sentence is above. Otherwise it gives the impression that the author of the comment is also the author of the sentence.

I think it is more intuitive to have the toolbar above the whole content, rather than in the middle between the sentence and the comment, too.  Toolbars usually go at the top.

screen shot 2016-09-12 at 09 09 31

**Pull request merged**
