### PR TITLE
Added language Berom

### LINKED ISSUE #2837: Berom (bom)
* Language name: Berom
* Language info: https://en.wikipedia.org/wiki/Berom_language
* ISO 639-3 code: BOM
* Public List: https://tatoeba.org/en/sentences_lists/show/169634
* Icon: https://imgur.com/a/U11TQlh
* Requested by: https://tatoeba.org/en/user/profile/AfricanQuant

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR closes #2837

### CODE REVIEW

**Comment by trang** [comment]
@sabretou If I'm not mistaken, Ricardo has included here the image provided directly by the requester of Berom. The letters for the ISO code are unfortunately quite hard to read (if you check https://github.com/Tatoeba/tatoeba2/blob/bbc10caca58803824f76a3703ce80f4c4cd4a93d/webroot/img/flags/bom.svg). Would you have time to craft an icon for Berom?

**Comment by sabretou** [comment]
@trang Ready!
bom

**Comment by trang** [comment]
Thanks @sabretou !

@RyckRichards Can you update the PR to use the new icon please :)

**Comment by RyckRichards** [comment]
@trang  Sure! :)

**Comment by RyckRichards** [comment]
Done! https://github.com/Tatoeba/tatoeba2/pull/2838/commits/cd47a479c46f38caa67c4cb2b8e39ffd01ba8116

**Pull request merged**
