### PR TITLE
Fix "Owned by a self-identified native" criterion

### LINKED ISSUE #2166: "Owned by a self-identified native" search criterion throws an error for English
## The Problem

At least for some advanced searches, "Owned by a self-identified native" gets an error message.

## Experiments: Things you can try

Here are several searches with only  minor differences, results sorted oldest first.
Only the first one results in an error message.

Query:  liquor|brandy|ale|absinthe|daiquiri|margarita|sangria|wine|tea|soda|smoothie|milkshake|milk|lemonade|juice|coffee|espresso|cappuccino|cocoa|grog|cola|beer|whiskey|bourbon|tequila|rum|cocktail|cider|martini|vodka|gin|"white russian"|"bloody mary"|"tom collins"|"hot chocolate"|"piña colada"|"soft drink"|"soda water"|"black cow"|"mint julep"|"egg nog"|"tonic water"|"mineral water"

Limited to native speakers  ** This one gets an error **

Search error
Invalid query. Please refer to the search documentation for more details.

https://tatoeba.org/eng/sentences/search?query=liquor%7Cbrandy%7Cale%7Cabsinthe%7Cdaiquiri%7Cmargarita%7Csangria%7Cwine%7Ctea%7Csoda%7Csmoothie%7Cmilkshake%7Cmilk%7Clemonade%7Cjuice%7Ccoffee%7Cespresso%7Ccappuccino%7Ccocoa%7Cgrog%7Ccola%7Cbeer%7Cwhiskey%7Cbourbon%7Ctequila%7Crum%7Ccocktail%7Ccider%7Cmartini%7Cvodka%7Cgin%7C%22white+russian%22%7C%22bloody+mary%22%7C%22tom+collins%22%7C%22hot+chocolate%22%7C%22pi%C3%B1a+colada%22%7C%22soft+drink%22%7C%22soda+water%22%7C%22black+cow%22%7C%22mint+julep%22%7C%22egg+nog%22%7C%22tonic+water%22%7C%22mineral+water%22&from=eng&to=und&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created&sort_reverse=yes

Limited to List 907 (1,000 results out of 4,499 occurrences)

https://tatoeba.org/eng/sentences/search?query=liquor%7Cbrandy%7Cale%7Cabsinthe%7Cdaiquiri%7Cmargarita%7Csangria%7Cwine%7Ctea%7Csoda%7Csmoothie%7Cmilkshake%7Cmilk%7Clemonade%7Cjuice%7Ccoffee%7Cespresso%7Ccappuccino%7Ccocoa%7Cgrog%7Ccola%7Cbeer%7Cwhiskey%7Cbourbon%7Ctequila%7Crum%7Ccocktail%7Ccider%7Cmartini%7Cvodka%7Cgin%7C%22white+russian%22%7C%22bloody+mary%22%7C%22tom+collins%22%7C%22hot+chocolate%22%7C%22pi%C3%B1a+colada%22%7C%22soft+drink%22%7C%22soda+water%22%7C%22black+cow%22%7C%22mint+julep%22%7C%22egg+nog%22%7C%22tonic+water%22%7C%22mineral+water%22&from=eng&to=und&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created&sort_reverse=yes

Has Audio  (1,000 results out of 3,069 occurrences)

https://tatoeba.org/eng/sentences/search?query=liquor%7Cbrandy%7Cale%7Cabsinthe%7Cdaiquiri%7Cmargarita%7Csangria%7Cwine%7Ctea%7Csoda%7Csmoothie%7Cmilkshake%7Cmilk%7Clemonade%7Cjuice%7Ccoffee%7Cespresso%7Ccappuccino%7Ccocoa%7Cgrog%7Ccola%7Cbeer%7Cwhiskey%7Cbourbon%7Ctequila%7Crum%7Ccocktail%7Ccider%7Cmartini%7Cvodka%7Cgin%7C%22white+russian%22%7C%22bloody+mary%22%7C%22tom+collins%22%7C%22hot+chocolate%22%7C%22pi%C3%B1a+colada%22%7C%22soft+drink%22%7C%22soda+water%22%7C%22black+cow%22%7C%22mint+julep%22%7C%22egg+nog%22%7C%22tonic+water%22%7C%22mineral+water%22&from=eng&to=und&user=&orphans=no&unapproved=no&has_audio=yes&tags=&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created&sort_reverse=yes

No limits (1,000 results out of 7,870 occurrences)

https://tatoeba.org/eng/sentences/search?query=liquor%7Cbrandy%7Cale%7Cabsinthe%7Cdaiquiri%7Cmargarita%7Csangria%7Cwine%7Ctea%7Csoda%7Csmoothie%7Cmilkshake%7Cmilk%7Clemonade%7Cjuice%7Ccoffee%7Cespresso%7Ccappuccino%7Ccocoa%7Cgrog%7Ccola%7Cbeer%7Cwhiskey%7Cbourbon%7Ctequila%7Crum%7Ccocktail%7Ccider%7Cmartini%7Cvodka%7Cgin%7C%22white+russian%22%7C%22bloody+mary%22%7C%22tom+collins%22%7C%22hot+chocolate%22%7C%22pi%C3%B1a+colada%22%7C%22soft+drink%22%7C%22soda+water%22%7C%22black+cow%22%7C%22mint+julep%22%7C%22egg+nog%22%7C%22tonic+water%22%7C%22mineral+water%22&from=eng&to=und&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created&sort_reverse=yes

I purposely avoided the "relevance" option because of https://github.com/Tatoeba/tatoeba2/issues/1895

### PR DESCRIPTION
**Pull request by jiru**
This PR fixes #2166.

It’s more of a work around than a real solution, but it solves the problem easily without creating additional problems.

I thought about adding a new Sphinx `native` attribute, but it’s much more complex to do, and I am afraid that if a member changes his/her nativeness in a language, we will need to update the attribute for all his/her sentences. If the member owns a lot of sentences, it’s gonna make the delta indexes grow very big.

### CODE REVIEW

**Comment by trang** [comment]
@jiru As mentioned in our weekly call, could you share your script to create lots of users for testing this?

**Comment by jiru** [comment]
Here is a script I used to insert of lot of native speakers locally:

```sh
#!/bin/bash

from=10
to=4106
echo 'begin;'
echo 'INSERT INTO `users` (`username`, `password`, `email`, `since`, `last_time_active`, `role`) VALUES'
for i in `seq $from $to`; do
  user=contributor_${i}
  echo -n "('$user', '1 $2a$10$ze.r64Pv1E.CTHUNFpFkVuqxuYlbj00aqqeRDd.kumCTIVtkZ/Q8C', '$user@example.net', NOW(), NOW(), 'contributor')"
  [ "$i" -ne "$to" ] && echo ","
done
echo ';'
echo 'INSERT INTO users_languages (of_user_id, by_user_id, language_code, level) VALUES'
for i in `seq $from $to`; do
  user=contributor_${i}
  echo -n "((select id from users where username = '$user'), (select id from users where username = '$user'), 'eng', 5)"
  [ "$i" -ne "$to" ] && echo ","
done
echo ';'
#echo 'rollback;'
echo 'commit;'
```

Pipe the script into mysql like this: `./insert_users.sh | mysql tatoeba`

**Comment by trang** [comment]
I've tested locally on my side. Didn't find any particular issue.

**Comment by trang** [comment]
Well now I'm finding issues. I was only focused on testing that there was no longer an error message but I did not pay enough attention to the search results. It seems that the "native" filter just has no effect anymore.

**Pull request merged**
