### PR TITLE
Added language Tahaggart Tamahaq

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR solves #1712.

### CODE REVIEW

**Comment by mozillakab** [comment]
The user who is now working on the tahaggart tamahaq (thv) is asking me to help him. HE is not confortable with Github.

HE created a list for Tamahaq and added all hi sentences to.

Here is the list of tamahaq sentences:  https://tatoeba.org/kab/sentences_lists/show/8456

**Comment by RyckRichards** [comment]
@mozillakab please ask him to pin @cueyayotl on https://github.com/Tatoeba/tatoeba2/issues/1712

**Comment by trang** [comment]
@RyckRichards keep in mind that the user is not comfortable with GitHub, he will not ping cueyayotl himself.

@mozillakab The list https://tatoeba.org/kab/sentences_lists/show/8456 contains sentences from several users and some of the sentences in there are in French... We cannot use this list to initialize the set of sentences in Tahaggart Tamahaq. Another list has been provided: https://tatoeba.org/eng/sentences_lists/show/8478. This list is good enough already, there is no need of another list.

Are you Aissimahfoud06, or is the user you are helping Aissimahfoud06?

**Comment by mozillakab** [comment]
@trang , @RyckRichards 
Thanks, I will tell him to put his sentences in the list you gave.
I'm not Aissimahfoud06, I know him as we are working together to translate sentences between Tamahaq and  Kabyle. Aissimahfoud06 is a teacher of Tamahaq.
I will try him train him on Github but I can also tel him to put his sentences in the list you provided.

**Comment by jiru** [comment]
@RyckRichards thanks! Please also remove the PNG file.

**Pull request merged**
