### PR TITLE
Avoid deletion of weekly export datafiles after zipping

### PR DESCRIPTION
**Pull request by LBeaudoux**
During the weekly exports, most of the generated data files are deleted once they are available in compressed form. It would be preferable to keep them, as they may be useful in the following use cases:
- [customized exports](https://github.com/Tatoeba/tatoeba2/pull/2636) from language-split data files
- [Todetect n-grams](https://github.com/Tatoeba/tatoeba2/issues/2671) update  by language

### CODE REVIEW

**Comment by jiru** [comment]
Looks good, thank you. 🙂 Could you maybe explain the reason you are doing this in your commit message? Explain that we need to keep uncompressed versions for other processings such as in Tatodetect.

**Comment by jiru** [comment]
@LBeaudoux Thank you for rewording the commit message. I suggest adding a multiline description in the commit message, see for example [this guide](https://chris.beams.io/posts/git-commit/) about how to write good commit messages.

I am having second thoughts on this PR. We are quite short on disk space on the production server and your PR increases the space used for exports by 2.1GB. Maybe I can free up some disk space here and there but basically we cannot really afford that at the moment. In addition, to know if it is really worth keeping uncompressed files, we’d have to measure the overhead of on-the-fly decompression when processing the files. Maybe it’s not that of a big deal.

**Comment by LBeaudoux** [comment]
@jiru Originally, this PR was primarily intended to speed up the generation of custom exports. But since [this](https://github.com/Tatoeba/tatoeba2/pull/2681) other pull request might have a similar effect without consuming as much storage. I don't see any harm in dropping it for now..

Thanks for your reading tips, it helps me improve.

**Comment by jiru** [comment]
In this case, I will close this PR for now. If the language pair export code ever gets rewritten to read data from the CSVs instead of the database, we can reconsider keeping uncompressed versions.

**Pull request closed without merging**
