### PR TITLE
Add check for authenticated user in Translate and Adopt Sentence Actions 

### LINKED ISSUE #1582: Some pages for contributors are accessible by non-authenticated users
Hi, I would find it a nice feature for not logged users to see, for pages that are only for members, a message telling that the page they want to see is only for registered members, I find that maybe it would be clearer to see.

### PR DESCRIPTION
**Pull request by danail-georgiev**
This resolves #1582. I asked Trang a question in the Issue's thread - is it better the redirection to be to the home page or to the Log-in page. If need be, I can make further changes to the MR.

### CODE REVIEW

**Comment by RyckRichards** [comment]
Thanks a lot for your PRs, Danail!!!! You're great!

>

**Comment by danail-georgiev** [comment]
Thanks @RyckRichards! Appreciated! :)

**Comment by jiru** [comment]
Hi there, thank you for your contribution. It looks good, and I hope it helped you to better understand our code base. :-)

I would like to suggest an alternative way of doing it though. You can manipulate the file config/auth_actions.php to restrict access to some controller actions. This file is used as a central place to define who is allowed to access what over the whole website. This way, you don't need to copy and paste the if block inside each and every controller action. In general, it's better to avoid redundant code (copy-paste).

The drawback of this method is that it cannot be used to redirect somewhere else that the login page. About that, I think redirecting to the login page is what we want, because it tells the user "to use this part of the website, you need to create an account first".

**Comment by jiru** [comment]
Also, maybe you noticed this already, but there is a red cross next to your commit. You don't necessarily need to do anything about this, but let me explain for the sake of learning.


The red cross means that the test suite failed. Every time somebody commits something, the new code is automatically checked against our test suite on https://jenkins.tatoeba.org. If you check the details of what failed, you'll see something like "Failed asserting that guest can access '/eng/activities/translate_sentences'." This is because we're testing that guests can access that page, as it is the expected behavior so far. Now that we decided that guests shouldn't be allowed (redirected), the test alerts us that the code isn't working as expected any more. The test suite helps us to avoid introducing regressions in the code. You can run the test suite locally using the command phpunit. https://github.com/Tatoeba/imouto/blob/master/README.md#tests


Obviously, here, the tests should be updated to reflect our new expectations in terms of who can access what. I'd like to encourage you to try updating the tests (relevant code is in tests/TestCase/Controller/ActivitiesControllerTest.php) but if you don't feel confident with that, it's okay. We can merge it first and fix the tests later.

**Comment by danail-georgiev** [comment]
@jiru  I tried to fix the issue the way you proposed but I cannot find a way to do it. Can you give me a hint or some explanation. Thanks in advance!

**Comment by AndiPersti** [comment]
What have you tried?

Do you understand the [output of Jenkins](https://jenkins.tatoeba.org/blue/organizations/jenkins/tatoeba2/detail/PR-2090/1/pipeline/) and know which tests failed?

We use PHPUnit for testing. Do you know [how to write tests for PHPUnit](https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html) and can you locate the failing tests in the file jiru mentioned?

**Comment by jiru** [comment]
When accessing a page, the controller name and action name are checked against what is defined in config/auth_actions.php.

First, it is checked against the public_actions array. If the page is there, it is displayed no matter if the user is logged in or not. For example, going to the page /collections/of/gillux will always work because it's defined in public_actions. Similarly, going to the page /activities/translate_sentences will always work because the wildcard allows all the actions of that controller.

Otherwise, if the requested page doesn't match anything in public_actions, it is then checked against auth_actions and the level of the user. For example, going to the page /audio/save_settings will work if and only if the user is logged in and has a level equal or higher than "contributor" (that is to say everybody except spammers and inactive accounts). Otherwise, it will redirect to the login page. Similarly, /collections/delete_sentence/1234 will also only work for logged in users because the wildcard restricts all the actions of that controller (except the ones like "of" that are catched earlier in public_actions).

I hope this helps. If you're still confused, feel free to ask some more specific question. Good luck! :-)

**Comment by danail-georgiev** [comment]
@jiru  and @AndiPersti , hi, I made some further changes as per discussion, I hope this is ok now :)

**Comment by AndiPersti** [comment]
Out of curiosity: Do you run the tests locally before committing any changes?

**Comment by danail-georgiev** [comment]
I have a problem locally and I cannot run the tests,  so I am counting on checking them against the Jenkins.

**Comment by AndiPersti** [comment]
What problem do you have? Do you get timeout errors?

I do get them on my machine. So for running the full test suite I need to set a higher time out limit: `COMPOSER_PROCESS_TIMEOUT=600 composer test`. This would set the timeout to 600s (10min). 

But you can also run just a single test file (e.g. `phpunit tests/TestCase/Controller/ActivitiesControllerTest.php`) or even just a single test (e.g. `phpunit --filter ActivitiesControllerAccess`). For more info see the [PHPUnit manual](https://phpunit.de/manual/6.5/en/textui.html#textui.clioptions).

**Comment by danail-georgiev** [comment]
I run the following command and i get this error:

vagrant@stretch:~/Tatoeba/tests/TestCase/Controller$ **phpunit ActivitiesControllerTest.php**
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

EEEEEEEEEEE                                                       11 / 11 (100%)

Time: 72 ms, Memory: 6.00MB

There were 11 errors:

1) App\Test\TestCase\Controller\ActivitiesControllerTest::testActivitiesControllerAccess with data set #0 ('/eng/activities/adopt_sentences', null, '/eng/users/login?redirect=%2F...%2Feng')
Use of undefined constant CONFIG - assumed 'CONFIG'

/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Routing/Router.php:1222
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Routing/Router.php:662
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/TestSuite/LegacyRequestDispatcher.php:53
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:513
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:397
/home/vagrant/Tatoeba/tests/TestCase/Controller/TatoebaControllerTestTrait.php:23
/home/vagrant/Tatoeba/tests/TestCase/Controller/ActivitiesControllerTest.php:44

2) App\Test\TestCase\Controller\ActivitiesControllerTest::testActivitiesControllerAccess with data set #1 ('/eng/activities/adopt_sentences', 'contributor', true)
Cake\Datasource\Exception\MissingDatasourceConfigException: The datasource configuration "default" was not found.

/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php:196
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:216
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/ORM/TableRegistry.php:149
/home/vagrant/Tatoeba/tests/TestCase/Controller/TatoebaControllerTestTrait.php:8
/home/vagrant/Tatoeba/tests/TestCase/Controller/TatoebaControllerTestTrait.php:18
/home/vagrant/Tatoeba/tests/TestCase/Controller/ActivitiesControllerTest.php:44
...................
11) App\Test\TestCase\Controller\ActivitiesControllerTest::testPaginateRedirectsPageOutOfBoundsToLastPage
Use of undefined constant TMP - assumed 'TMP'

/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Http/Session.php:153
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Http/Session.php:97
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:612
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:516
/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:397
/home/vagrant/Tatoeba/tests/TestCase/Controller/ActivitiesControllerTest.php:52

ERRORS!
Tests: 11, Assertions: 0, Errors: 11.
vagrant@stretch:~/Tatoeba/tests/TestCase/Controller$

**Comment by agrodet** [comment]
@danail-georgiev As mentioned by @AndiPersti, use `phpunit tests/TestCase/Controller/ActivitiesControllerTest.php` from the `Tatoeba` folder

**Comment by trang** [comment]
@jiru I reached out to Danail and he told me that he will not have time to finish his pull request so we can just take over. I'll let you check what to do with this one and the other one (#2167). Feel free to just close if it's too much trouble to merge.

**Pull request merged**
