### PR TITLE
add UTC to tooltip datetime

### PR DESCRIPTION
**Pull request by polkadotazn**
I added UTC as part of the `nice(date)` method. I updated the Date Helper tests as well.

### CODE REVIEW

**Comment by RyckRichards** [comment]
Thanks for this PR, @polkadotazn

**Comment by trang** [comment]
@polkadotazn Congratulations on your first pull request 🥳

Tip: you don't need to comment on the associated issue every time you open a PR. Do mention which issue your PR is solving in your description though. GitHub will take care of creating links between the issue and the PR. And if you use some [special keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) before the issue reference (for instance "This PR fixes #2319"), it can automatically close the associated issue once your PR is merged.

We'll get back to you soon for the next issue :)

**Comment by jiru** [comment]
@polkadotazn Nice! And good job with updating the tests too. :blush:

There is just one problem with your implementation. It doesn’t allow "UTC" to be translated. In other words, it is alright when the website is displayed in English, but other languages might look weird with that English acronym thrown inside.

Localization of dates and time is actually a tedious problem. That’s why we rely on special methods like [`Time::nice()`](https://book.cakephp.org/3/en/core-libraries/time.html#Cake\I18n\Time::nice). The format used by `nice()` is defined at the end of `config/bootstrap.php`:
https://github.com/Tatoeba/tatoeba2/blob/bb839f64b7693e9eaa419b7d5e8b3812bea7cda2/config/bootstrap.php#L272

That array consists of two constants: one for the format of the date, and the other for the format of the time. These are [constants from the ICU library](https://www.php.net/manual/en/class.intldateformatter.php#intl.intldateformatter-constants), which job is to localize dates while abstracting out all the language specifics. So ideally, we want to tell the ICU library to just "format the datetime including the timezone" and let it do the job. According to the documentation on php.net, it looks like you could use `IntlDateFormatter::FULL` to get the timezone included. Could you try that?

**Comment by AndiPersti** [comment]
> So ideally, we want to tell the ICU library to just "format the datetime including the timezone" and let it do the job. According to the documentation on php.net, it looks like you could use IntlDateFormatter::FULL to get the timezone included.

Unfortunately there are a few more things to consider:
1. Most languages use `GMT` instead of `UTC`
2. All ICU format levels from `MEDIUM` upwards include the seconds in the time (which we currently do not).
3. The current version of `DateHelper` uses the same `nice` format for the text and the tooltip.

Example (using `IntlDateFormatter::FULL`):
date

**Comment by jiru** [comment]
What about using `IntlDateFormatter::FULL` only in tooltips?

**Comment by polkadotazn** [comment]
Ok definitely! Thanks for the feedback!! I will try that. Unfortunately I spilled a bit of water on my laptop yesterday and I am leaving it off for a couple days to dry out 😨

**Comment by jiru** [comment]
Oh, no! :hushed: I hope your laptop will survive. You can also try to completely cover your laptop components with (uncooked) rice. Over time, the rice should suck up all the moisture.

**Comment by Yorwba** [comment]
FWIW, the people at [iFixit recommend using isopropyl alcohol to displace the water instead](https://www.ifixit.com/Wiki/Don%27t_Put_Your_Device_in_Rice._Here%27s_Why...) of letting the device dry (in rice or otherwise), because the water can keep corroding components inside while you wait.

**Comment by AndiPersti** [comment]
That's what I would suggest too.

But `TimeHelper::nice()` doesn't take a format and just uses the one defined in `bootstrap.php`. So the date formatting for tooltips needs to use [`TimeHelper::format()`](https://api.cakephp.org/3.7/class-Cake.View.Helper.TimeHelper.html#_format).

**Comment by jiru** [comment]
Maybe you can use `TimeHelper::i18nFormat()` instead of nice() for the tooltip.

**Comment by polkadotazn** [comment]
ok sounds good! I'll look into these options. thanks everyone for these suggestions and also the computer tips :D

**Comment by jiru** [comment]
> Example (using `IntlDateFormatter::FULL`):
> date

@polkadotazn That screenshot is actually using `IntlDateFormatter::LONG`. `IntlDateFormatter::FULL` spells out the whole words of the timezone.

**Comment by jiru** [comment]
See #2368.

**Pull request closed without merging**
