### PR TITLE
New buttons

### PR DESCRIPTION
**Pull request by trang**
This pull requests is part of phase 1 of the UI migration (cf. issue #1180).

In this pull request, most of the buttons have been migrated to use the buttons from the Angular Material framework.

The color used for the buttons corresponds to the `green` color in the Material Design palette.
https://www.google.com/design/spec/style/color.html

In the process, the background color of the search bar and the color of the links have been changed as well, to match the color of the buttons.

Overall, users should not feel a huge change.

### CODE REVIEW

**Comment by Guybrush88** [comment]
the text within the button to submit a translation is still truncated

**Comment by trang** [comment]
I don't see it truncated.

screenshot_4

**Comment by billoliver** [comment]
I think we should change the wording to something shorter like "submit".

**Comment by Guybrush88** [comment]
@trang yep, now it's fixed also for me. maybe i saw it still truncated for cache related things

**Comment by Guybrush88** [comment]
I don't know if it's a known issue, but on dev, the button to copy a sentence into the clipboard stopped working again

**Comment by RyckRichards** [comment]
+1

Also on the main Tatoba

**Comment by Guybrush88** [comment]
on the main site, it works for me

**Comment by trang** [comment]
I modified the code on the dev website for Ricardo to test certain things. Right now it's reverted back to normal so the copy feature should work again, but don't be surprised in the next couple of weeks if some features are not working on the dev website.

**Comment by Guybrush88** [comment]
Is it normal that, if a sentence is edited and it takes a while to save the changes, no loader appears? This happens on both the normal and dev sites, and this didn't happen with the previous icons

**Comment by trang** [comment]
No it's not normal.

By the way for issues related to loaders you should comment on  #1194.

In general, for issue related to the UI, you should check what has been done in #1180. You can look at issues that reference to #1180, and you can report problems on the corresponding "sub-issue". If you can't find a sub-issue that covers your problem, then you can post a comment on #1180.

**Pull request merged**
