### PR TITLE
Avoid total text from wrapping

### PR DESCRIPTION
**Pull request by lex111**
| Before   | After    |
| -------- | -------- |
| image | image |

cc @trang

### CODE REVIEW

**Comment by trang** [comment]
Hi @lex111, sadly I can't merge it because I've got some work in progress for the homepage. I mean, I could merge, but the things you changed will have no effect because the whole stats block is going to be either removed, or redesigned... Sorry :S 

Thanks for the merge request nonetheless! :)

**Comment by lex111** [comment]
@trang I got you, but the new homepage is **not** ready yet? Why not accept my change until you finish this one? :man_shrugging:

**Comment by trang** [comment]
@lex111 Because it's almost ready. I have the changes locally, it's just not pushed yet. You timed your pull request for the week where I had plans to make the changes for the homepage...

I could merge the pull request but it would just be overriden by my own changes :P

Screenshot_2019-09-27 Tatoeba Collection of sentences and translations

**Comment by lex111** [comment]
@trang fine fine.. if you push your changes today xD

P.S. I'm interested in the project, maybe I will do something else!

**Comment by trang** [comment]
Okay, I will push today :) I wanted to push this since last week actually but got sidetracked by existential questions about language flags...

Glad to know you're interested in the project, let me know if I can help in something. We'll always be in need of more devs!

**Pull request closed without merging**
