### PR TITLE
Search by original or translation

### PR DESCRIPTION
**Pull request by jiru**
Solves #2159.
search1
search2

### CODE REVIEW

**Comment by jiru** [comment]
Related: #1643.

**Comment by LBeaudoux** [comment]
It seems a bit clunky to me. Wouldn't a "Not derived from another sentence (original)"l checkbox at the bottom of the form be more appropriate?

**Comment by alanfgh** [comment]
Rather than "Not as translation (original)", I would suggest one of these:

- Not as a translation
- Original

I agree that using both of them together sounds clunky.

While "Original" is concise and natural, I'm guessing that the objection to it is that people can add sentences that they take from elsewhere as long as they are in the public domain, so they're not original in the sense of having been authored by the owner. In the context of a drop-down list where one of the other alternatives is "Not as a translation", this interpretation is less likely, but still possible, I suppose. So my vote is for "Not as a translation" (note that I do prefer the presence of "a" before "translation"). However, I could also live with "Original".

_> Wouldn't it be more appropriate to have a checkbox at the bottom of the form that says "Not derived from another sentence (original)"?_
My guess is that this is offered as an alternative to the drop-down list, and assumes that people are not going to want to search explicitly for "Unknown" or "As a translation of another sentence". However, I think it's better to have this added flexibility, given that it's on an advanced search dialog that already offers this level of granularity for other choices.

**Comment by LBeaudoux** [comment]
> My guess is that this is offered as an alternative to the drop-down list, and assumes that people are not going to want to search explicitly for "Unknown" or "As a translation of another sentence". 

To be honest, I can't think of a use case in which a user would specifically search for derived sentences...  Also, I find the label `not a translation` misleading because an original sentence is the back-translation of a sentence that is derived from it.
How about a simple checkbox labelled `in the original language`, as for movies?

**Comment by jiru** [comment]
Thank you for your feedback. You both have solid points and it’s difficult to make a decision. One could argue that the other, existing filter "Owned by a self-identified native" does not offer such level of granularity (there is no "not owned by a self-identified native" filter, even though I can see a use case). I generally think that we should avoid unnecessary complex UIs, and the advanced search is already quite complex. My original aim was to only show original sentences, so I am going to stick with a simple checkbox until there is need for other filters.

**Comment by jiru** [comment]
Alright this is what I came up with:
* simpler "Is original" labelled checkbox
* infobox with text appearing on mouseover/tap: Original sentences are the ones initially added as examples in that language only, as opposed to the ones initially added as translations of another sentence. Such sentences are likely to feature more traits specific to that language.

Feedback welcome!

shot

**Comment by LBeaudoux** [comment]
@jiru thank you for these changes.

Here's what I think could be improved:
 - Move the new checkbox below the "added by a self-identified native" checkbox, which has a similar purpose, appearance and priority.
 - Shorten the text of the infobox. I suggest  _The sentences in the original language are not added by translating other sentences. They often sound more natural_.

**Comment by LBeaudoux** [comment]
> Personally, I will rarely use these two checkboxes, but I filter by list very often.

What if we introduced even more changes? I suggest:
- move the two checkboxes just below `Length`.   
- move `Tags` and `List` below `Owner`

**Comment by jiru** [comment]
Well I never filter by list. I think I just opened a can of worms :smile:

We might as well try to improve fields order in another ticket.

**Comment by jiru** [comment]
@alanfgh I simplified the search option design, could you review the English used in the [infobox text](#issuecomment-2290842738) please?

**Comment by alanfgh** [comment]
Are you talking about this text?

> Original sentences are the ones initially added as examples in that language only, as opposed to the ones initially added as translations of another sentence. Such sentences are likely to feature more traits specific to that language.

I agree with @LBeaudoux that it should be shorter. In addition, I don't see why it's necessary to say anything about the relative worth of original sentences vs. non-original. I don't even believe that original sentences are better; they could just as easily be added by someone who's a poor non-native speaker or a sloppy native speaker. In any case, the whole reason for supplying this option is that we think people want it. We don't need to try to convince people to search for these sentences.

With that in mind, I suggest simply:

_Original sentences are ones that were not added as translations of other sentences._

**Comment by jiru** [comment]
Thank you @alanfgh for your insightful comment, I totally agree. I updated the infobox text.

**Comment by jiru** [comment]
Note: we will need to do a full reindexation of manticore indexes during deployment, like this:

```sh
# 5.
cd /var
./create-new-prod-folder.sh --no-dry-run

# full reindexation
screen -S reindex
crontab -e # disable reindexation tasks refresh_delta.sh and merge_indexes.sh
SHA=...
sed -i "s/www-prod/www-prod-$SHA/" /etc/manticoresearch/manticore.conf
www-prod-$SHA/bin/cake sphinx_indexes update main && www-prod-$SHA/bin/cake cake sphinx_indexes update delta -f
sed -i "s/www-prod-$SHA/www-prod/" /etc/manticoresearch/manticore.conf

# 6.
./set-prod-folder.sh {SHA}

# restore automatic reindexation
crontab -e # enable reindexation tasks refresh_delta.sh and merge_indexes.sh

# 7.
systemctl reload php7.3-fpm
```

**Pull request merged**
