### PR TITLE
Add mail icon with a link for writing a new message

### PR DESCRIPTION
**Pull request by danail-georgiev**
(#1718) I created a draft MR because I am not quire sure how to fix a couple of problems. 

First, If someone can advise me on the styling of the icon (height, width, color, if the tags used are the appropriate ones) . 

Second, the data label disappears after the icon is rendered but I guess this is related to the aforementioned issue with the height of the icon.

### CODE REVIEW

**Comment by AndiPersti** [comment]
First, thanks for helping out with the code. I've also just started to participate a few months ago and experienced some difficulties at the beginning. :-)

> First, If someone can advise me on the styling of the icon (height, width, color, if the tags used are the appropriate ones) .

The Material Design tags/directives (the ones starting with `md-`) are correct but I don't think you need the outer `span` tag.
Styling of the icon should happen with CSS classes which leads us to your second question:

> Second, the data label disappears after the icon is rendered but I guess this is related to the aforementioned issue with the height of the icon.

The date label "disappears" because the styling you've applied to the button (`class="md-icon-button"`) makes the button too big and too centered and thus the date label moves too far down.
Do you know how to use the developer tools of your browser? If you select the button and disable some properties of the `md-button` class (e.g. `margin`, `min-height`, `line-height`) you'll notice that the date line will reappear.
So you need to add some extra styling for the button.

BTW: I guess you should also prefill the recipient of the private message. See for example https://github.com/Tatoeba/tatoeba2/blob/dev/src/Template/Element/users_menu.ctp on how you can pass a parameter to the controller.

**Comment by danail-georgiev** [comment]
Hi Andi, 

Thanks for the feedback! To be honest I don't know exactly how to style the button using css - I checked the css files in the webroot but still I am not able to completely understand how to structure my changes. If you can be more specific how exactly I should implement the changes, it would be welcome. (I am aware of the Web Dev tools of course but I would like to understand how exactly to include the css file in the project).
Thanks for the link, I will have a look and try to fill in the recipient of the message.

**Comment by trang** [comment]
Note that the screenshot on #1718 was a screenshot of how the comments used to look like and we actually don't want to have the exact same display. Therefore in this case, there's no need to worry about styling the icon. Simply add the message icon next to the other existing icons, keeping the same default color and size.

Screenshot_2020-01-15 Tatoeba Collection of sentences and translations

Regarding the CSS structure, the code that includes the CSS is in the [layout.ctp](https://github.com/Tatoeba/tatoeba2/blob/dev/src/Template/Layout/default.ctp#L40). But in summary:
- The CSS files in the [layouts](https://github.com/Tatoeba/tatoeba2/tree/dev/webroot/css/layouts) folder will be included on every page.
- Then for each page, there's one additional CSS file included. This file is in the folder named after the controller and is named after the action. So if you are on the sentence's page (controller = sentences, action = show), then [/sentences/show.css](https://github.com/Tatoeba/tatoeba2/blob/dev/webroot/css/sentences/show.css) will be included.

Supposing you would want to have a special color for your the private message icon, you could add the CSS in the `elements.css` file (because the icon can be found on several pages). Alternatively, you can also just add the style inline (`style="color: red"`).

**Comment by danail-georgiev** [comment]
I made further changes, I think that now it is ok. Thanks for the help @AndiPersti and @trang :)

**Comment by AndiPersti** [comment]
Maybe don't add the icon if the comment author is the current user?

Otherwise it looks fine to me. :-)

**Comment by danail-georgiev** [comment]
@AndiPersti  yes, thanks for the correction, added

**Pull request merged**
