### PR TITLE
Added language Baluchi (bal)

### LINKED ISSUE #2418: Baluchi (bal)
* Language name: Baluchi 
* Language info: https://en.wikipedia.org/wiki/Balochi_language
* ISO 639-3 code: BAL
* Public List: https://tatoeba.org/eng/sentences_lists/show/166707/eng
* Icon: https://junaidqadir.com/baluchi-icon/bal.svg
* Requested by: https://tatoeba.org/eng/user/profile/junaidqadir

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR closes #2418.
It adds Baluchi (bal) on Tatoeba.

### CODE REVIEW

**Comment by jiru** [comment]
@RyckRichards You don’t need to convert it, you can leave it as SVG. Good job with getting your hands on the SVG, by the way! :+1:

Also please check my [other comment](https://github.com/Tatoeba/tatoeba2/issues/2418#issuecomment-652526191).

**Comment by jiru** [comment]
One more thing: it looks like this language is written from right to left, so you should add it to the appropriate array.

**Comment by jiru** [comment]
Thanks, it’s all good now. :+1: I will merge it next week.

**Comment by JunaidQadirB** [comment]
Thanks!

**Comment by RyckRichards** [comment]
I believe we can add it on prod. They are making a fast progress

image

**Comment by trang** [comment]
@RyckRichards, similarly to #2434, the default.pot is still only 39% translated. Shouldn't we wait till it reaches ~80%?

**Comment by RyckRichards** [comment]
@jiru The Balochi (بلۏچی‎ ) translators almost finished translating the UI, I believe we can enable it on prod

image

https://www.transifex.com/tatoeba/tatoeba_website/translate/#bal

**Comment by jiru** [comment]
I enabled Baluchi on tatoeba.org. :tada:

**Comment by RyckRichards** [comment]
That's great! Thank you!

**Comment by JunaidQadirB** [comment]
Thank you very much @RyckRichards, 
One issue though, the link you posted is not working.

I really appreciate everyone that helped us add Balochi to the Tatoeba2 project.

**Pull request merged**
