### PR TITLE
Language configuration file updated and added Frisian

### PR DESCRIPTION
**Pull request by robin0van0der0v**
I updated the language configuration file so that it contains all languages currently enabled on Transifex. I also added Frisian to the core language file, as the translation is nearing completion. It is currently at 74 %.

### CODE REVIEW

**Comment by trang** [comment]
Thanks a lot for your pull request @robin0van0der0v =)

There are a few things missing in your PR.

There is documentation about how to add a new UI language in the `README.md` of the `app/locale` folder: https://github.com/Tatoeba/tatoeba2/tree/dev/app/locale#ui-translations

Unfortunately the documentation is not 100% up to date, and I'd like to update it so you can complete your pull request, but I probably won't have time this week... Hopefully next week.

**Comment by robin0van0der0v** [comment]
I tried my best in following that guide already, but there were some inconsistencies. If you or somebody else tells me what is missing, I will add it gladly to my pull request.

**Comment by trang** [comment]
I will. Next week. Hopefully. 

I will review the README, and will let you know when I have updated it so you can use it as a reference to complete your pull request.

**Comment by trang** [comment]
Okay, I have reviewed the instructions. It turns out you have nothing else to do :)

**Comment by RobinvanderVliet** [comment]
Frisian is currently still not available on Tatoeba. Why is this?

**Comment by trang** [comment]
The decision to activate a new UI language depends on how much of the UI has been translated into the language, if there are active translators for this language, and whether or not we have a lot of requests to make the language available.

It's in the end a subjective evaluation but Frisian seems to not be ready yet.

Also we are more careful about adding new UI languages now than in the past because we cannot remove a UI language so easily (cf. #725).

**Pull request merged**
