### PR TITLE
Issue #1832: "Cache" the search we do in "advanced search"

### PR DESCRIPTION
**Pull request by jpear1**
I'm opening this PR to start a discussion about how to implement a solution to #1832.

Here's my thoughts so far:

Search caching should be the default, a user shouldn't have to do anything to enable it. So if a user does a search then presses "back", or just refreshes the page, their search should be just as they left it. Basically just copy the behavior of Google's advanced search.

If people sometimes use the existing behavior, we could add a "reset all" button on the form.

This would solve two of the use cases from #1832: 
* *do the same research again*
* *do a "likely" research "most of the parametres are the same but some not - like "exclude/include" sentences that ... / show translations in ...*

The third use case, "*share the search for a friend (not the final result)*" could be implemented separately, perhaps via `$_GET`. I believe this would also allow bookmarking a search.

I did some googling and it looks like there's a couple of options for caching the search: cookies and sessions.

By my understanding, cookies are easier to use, but sessions prevent hackers from being able to access data they shouldn't be able to.

Any and all concerns/advice welcome. Especially on cookies vs sessions and how they would be implemented CakePHP/Angular.

### CODE REVIEW

**Comment by jiru** [comment]
Sorry for the late reply! :pray: 

> Search caching should be the default, a user shouldn't have to do anything to enable it. So if a user does a search then presses "back", or just refreshes the page, their search should be just as they left it. Basically just copy the behavior of Google's advanced search.

What you describe as the default behaviour of keeping form values isn’t so easy to do because the caching behaviour differs among browsers. Some might keep the values while others won’t. That said, right now we are explicitly telling browsers not to cache the page (using HTTP headers Cache-Control and Pragma), so users have no chance to see their search criteria back when pressing the back button:

```
$ curl -v https://tatoeba.org/jpn/sentences/advanced_search 2>&1 >/dev/null | grep -i cache
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
```

For the record, this wasn’t the default behaviour until we switched from Cakephp 2 to CakePHP 3 last year, and [somebody noticed it](https://github.com/Tatoeba/tatoeba2/issues/1833). So I think a good first step would be to disable caching on the advanced search page so that users have a chance to get back the data they entered when pressing the "back" button.

From there, since the restoring the values might still not work on some browsers, so it’s best to store the data in session/cookies as well to make it bulletproof.

> I did some googling and it looks like there's a couple of options for caching the search: cookies and sessions.
> 
> By my understanding, cookies are easier to use, but sessions prevent hackers from being able to access data they shouldn't be able to.

It depends on the context, because after all, what we call a session is actually a cookie containing an identifier granting you access to the data remotely. So in both cases, you need to access a cookie first in order to get access to the data. In your case, giving how large the amount of data you want to store is (all the search fields), it makes sense to use [sessions](https://book.cakephp.org/3/en/development/sessions.html#accessing-the-session-object).

> The third use case, "*share the search for a friend (not the final result)*" could be implemented separately, perhaps via `$_GET`. I believe this would also allow bookmarking a search.

Yes, that’s a good idea. Something like https://tatoeba.org/jpn/sentences/advanced_search?query=foobar. See the documentation about [Modelless forms](https://book.cakephp.org/3/en/core-libraries/form.html). This should be easy to implement as we already have a form for the search in `src/Form/SentencesSearchForm.php`. You could add a "permalink to this search criteria" link/button on the form. I think the best way to do that is to use the [`formaction`](https://developer.mozilla.org/en/docs/Web/HTML/Element/input/submit#formaction) HTML5 attribute on a new button.

So I identified 3 things you can do so far to improve the situation:
1. Enable caching of the advanced  search page
2. Add a "permalink to this search criteria" link/button
3. Store field values in session

Of course any other suggestion is welcome. Feel free to open a new PR for each of these. I think 1. has the best value/effort ratio so I suggest starting with this if you are familiar with HTTP headers and browser caching. 2. should be easy to implement as well if you are familiar with front-end code. 3. is certainly the hardest.

Here are some pointers to where is what in the code:
* Searches are performed by the `search()` method in `src/Controller/SentencesController.php`.
* The advanced search page is first handled by the `advanced_search()` method in `src/Controller/SentencesController.php`, and then the form is displayed by `src/Template/Sentences/advanced_search.ctp`
* The actual search form is displayed by `src/Template/Element/advanced_search_form.ctp`. This code is used both in the Advanced search page and on the right side of the search results.

**Comment by trang** [comment]
> Search caching should be the default, a user shouldn't have to do anything to enable it. So if a user does a search then presses "back", or just refreshes the page, their search should be just as they left it. Basically just copy the behavior of Google's advanced search.

For this specific use case, if the user wanted to perform another search with just one different criteria, technically they wouldn't really need to press "back" in order to readjust their search. We display the advanced search form along with the search results so they can make adjustments from there.

I'm not sure if we have enough evidence to assume that when a user who goes back to the advanced search form, they will generally prefer to see their latest search rather than an empty form.

It was mentioned in #1498 that some users have been annoyed/confused about the fact that the inputs in the green search bar were kept in session. Perhaps we should put aside the idea of storing the search criteria in session, or at least until we can justify that no one wants to see an empty form by default?

Event though the title of the #1832 mentions "cache", I think the need is not to cache but to be able to load *quickly* search criteria. It is possible to bookmark and load predefined search criteria, by bookmarking search results, but loading these predefined criteria currently comes with the cost of performing an unnecessary search. In some cases, waiting for the results may just take as much time as filling up manually an empty form.

I personally would suggest to first only implement this "permalink" that can be bookmarked/shared and see if is sufficient to the users needs.

**Comment by jpear1** [comment]
Alright, makes sense. Adding permalinking does seem like the least objectionable change. I'll start there.

One reason I think it may be useful to store the search parameters in session is that the advanced search page is a lot easier to read than the sidebar you see beside your search results. Not all of the parameters fit on the screen (you have to scroll down), and some of the sentences are kind of a pain to read. Ex. "Limit to sentences having translations that match all the following criteria" takes three lines. When I first started using Tatoeba, I tried to go back and modify my search on the original advanced search page for just this reason.

**Comment by trang** [comment]
I'm closing this PR since there's another one open.

**Pull request closed without merging**
