### PR TITLE
 added Ge'ez transcription for Tigrinya / Amharic. Changed Georgian t…

### PR DESCRIPTION
**Pull request by oyd11**
…ranslitaration to match ISO-9984 and Wikipedia/Wiktionary

### CODE REVIEW

**Comment by jiru** [comment]
Thank you, oyd11, but I don’t think we can merge your pull request.

First, [it’s not clear to me wether we should continue adding transcriptions, since their usefulness is controvesed](https://tatoeba.org/wall/show_message/21405#message_21405). To sum up the problem, there are situations where native speakers use several scripts concurrently, such as simplified and traditional characters for Chinese. In this case, transcribing from one script to another is perfectly fine because it helps native speakers writing sentences in their mother tongue, which is one of the primary goals of Tatoeba. However, when a transcription is not needed by native speakers, but only to learners (or worse: only intelligible to learners), one can consider it attracts very-low-level contributors since learning the writing system is one of the very first steps a learner should do. Some transcriptions lack a proper standard or have other problems. So whatever we decide needs to be debated on the Wall first.

Second, your code needs to be improved before we can merge it. I did not review it thoroughly, but here a few things that would need to be fixed:
* Remove usage of `global`. You can declare your arrays `$geezConsBase`, `geezPuncTable` etc. as private attributes of `Autotranscription` and access them from within functions using `$this`.
* `geezNum2Latin()` is a bit too obscure, in particular the bitwise operations. Add comments or break it down into subfunctions with meaningful names.
* I strongly suggest you try to avoid calculating unicode code points and using them directly because it makes your code obscure and error-prone. It’s certainly easier and safer to use [unicode properties](http://www.regular-expressions.info/unicode.html) instead. There are properties like `\p{Ethiopic}` and `\p{Punctuation}`.
* You’re using your conversion tables without prior checking of key existence (using `isset()` or `array_key_exists()`).
* The indentation is somewhat inconsistent. Never use tabs and always follows the indentation style of the existing code.

Finally, I’m in the process of totally rewriting the transcription code in #661, so it would be better to base any new transcription system on that branch instead.

**Comment by trang** [comment]
> First, it’s not clear to me wether we should continue adding transcriptions, since their usefulness is controvesed.

I think we can add transcriptions as long as they are made optional. I'm personally in favor of hiding by default all transcriptions/transliterations, and display them only if the user activates the option.

This would of course imply warning our users about the change, which we could do with the announcement system (#925).

One thing to consider though is whether it's fine if this option would be available only for registered users or if we should implement an options system for non-registered users. I'd guess that it's fine to "force" users to register to have access to transliterations and transcriptions, but maybe I'm wrong.

> Finally, I’m in the process of totally rewriting the transcription code in #661 

Do you have any rough idea of how much work you still have to do until this branch will be ready to be merged? Just to know if it's a matter of a couple of weeks, or a couple of months, or half a year?

**Comment by jiru** [comment]
> Do you have any rough idea of how much work you still have to do until this branch will be ready to be merged? Just to know if it's a matter of a couple of weeks, or a couple of months, or half a year?

There is not much work remaining, mainly fix a few bugs and find an icon. We may go with a new round of tests on dev.tatoeba.org in a week or two and eventually merge it. But there are also some unsettled questions (see the PR page) I’m not sure how to deal with.

**Comment by oyd11** [comment]
Hello guy, sorry for the late reply::
So @jiru :: I agree with the coding style comments, and apologise - I have very little coding experience in PHP - and thus found the solutions I could for issues (eg, I couldn't made the code work without the _global_ variables), I would appreciate any revision of the code. As you say your branch will be merged soon - and I do see the surrounding code on your branch is much cleaner anyhow - I could try to re-implement this after you merge back into the 'master' branch.
 As for the _bitwise_ operations - that's part of how Ge'ez Consonant/Vowels are encoded in Unicode, yes, it's way better to self-document it in the code somehow.

As for adding or not adding transliterations - it seems these discussions on the harmfulness of transliteration are all ignoring the case of Digraphia [ https://en.wikipedia.org/wiki/Digraphia ], specifically - Serbian and Serbo-Croatian - were (as implemented in Wikipedia) some readers of the same language - prefer to read it in a different alphabet, and the transliteration is 1-1.

It also seems to me like the whole argument is centred around some social issues with Japanese learners who confuse the site with "lang-8.com".

Another important case (which is the case with transliterating Ge'ez) - is having close sister-languages with different alphabets, in the case of Ge'ez - other Semitic language speakers (speakers of Arabic, Hebrew and Maltese) - may want to see how something is pronounced in Amharic or Tigrinya and might recognise most words, without learning the alphabet. Also - a lot of diaspora speakers of Amharic and Tigrinya speak fluently and do not read the alphabet (but are familiar with the Latin alphabet), from the social context I know with these languages - these might be the majority of prospective learners (who want to improve their home language, and learn the alphabet on the way), I see the alphabet is a big obstacle for them.
[this is not unique to Semitic again, a similar situation exists with even closer Turkic languages written in Latin vs Cyrillic and I'm sure many others]

**Comment by jiru** [comment]
I’m okay to add new transcriptions as long as they are justified, and your arguments are convincing.

Another thing that would be very much appreciated would be tests (or data to make tests). A test is a simple code that executes the transcription algorithm against a given string and verify that the output is as expected. This requires a list of source→transcription sentences that are considered correct. It’s important because it allows developers (like me) to work on the transcription code without being native or linguists. If you can provide me with such a list, I will be able to help you out.

**Comment by oyd11** [comment]
Sure, I have test sentences, and there should be a test of the whole alphabet blit'ed in.
As Trang suggests - I'll make the "revised Georgian" and "Ge'ez" - separate commits. For now I'm waiting for your merge then.

**Comment by jiru** [comment]
My branch is now merged. If you’re still interested in adding Ge’ez transcription, please follow [this guide](http://en.wiki.tatoeba.org/articles/show/new-transcription-request).

**Pull request closed without merging**
