### PR TITLE
Added language Rusyn

### PR DESCRIPTION
**Pull request by RyckRichards**
This pull request addresses #1212 .

### CODE REVIEW

**Comment by trang** [comment]
@RyckRichards, can you rebase your branch. Thank you!

**Comment by RyckRichards** [comment]
Done :)
http://prntscr.com/bmlr16
https://github.com/RyckRichards/tatoeba2/network

**Comment by trang** [comment]
@RyckRichards, you deleted your commit. This pull request is currently empty.

**Comment by RyckRichards** [comment]
That's weird... I've created a gist - https://gist.github.com/RyckRichards/e4606f80aed26f8f728f4cbe931d18fa

**Comment by trang** [comment]
I can't view the gist at the moment. Simply re-commit your changes.

**Comment by RyckRichards** [comment]
gotcha!

On 6/29/16, Trang <notifications@github.com> wrote:
> I can't view the gist at the moment. Simply re-commit your changes.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatoeba/tatoeba2/pull/1213#issuecomment-229375297


-- 
Ricardo Vernaut Jr

**Pull request closed without merging**
