### PR TITLE
Add Chinese Jinyu as UI language

### PR DESCRIPTION
**Pull request by RyckRichards**
This PR adds Chinese Jinyu on Tatoeba in order to help translators to check how their translations are rendering.

### CODE REVIEW

**Comment by jiru** [comment]
@RyckRichards I am not a native speaker, but I don’t think the language name 简体中文 means "Chinese Jinyu". "简体中文" means "Chinese using simplified characters" (that is to say Mandarin). The UI is already translated in Chinese (using simplified characters) using the ISO code is cmn (zh_CN on Transifex) and the language name 中文 ("Chinese"). Shouldn’t "Chinese Jinyu" be something like 晋语/晉語?

**Comment by RyckRichards** [comment]
I asked that to a translator who is translating Tatoeba UI into Chinese Jinyu and he gave me that. I'll make a "deeper" research.

**Comment by jiru** [comment]
I just hope that the translator didn’t re-translate the UI in Mandarin…

**Comment by RyckRichards** [comment]
Goot catch! I'll compare both translations to make sure everything is OK in there

**Comment by RyckRichards** [comment]
Since the translators and native speakers replied to [this query](https://github.com/Tatoeba/tatoeba2/pull/2454#issuecomment-659715788), I'm closing it.

**Comment by jiru** [comment]
@RyckRichards I’m confused. What was their reply?

**Comment by RyckRichards** [comment]
Sorry, I wasn't clear. I've noticed that now.
No one has replied to this query.

**Pull request closed without merging**
