### PR TITLE
Make user sidebar menu collapsible

### PR DESCRIPTION
**Pull request by AndiPersti**
This PR addresses #2023

### CODE REVIEW

**Comment by AndiPersti** [comment]
[deniko raised a related issue on the wall](https://tatoeba.org/deu/wall/show_message/33862#message_33862) which this PR currently doesn't address.

The problem with the reflow could be solved by either adding the `ng-cloak` directive to the language filter element or to the whole sidebar (the latter would also improve other pages which have additional elements below the user menu in addition to the language filter, e.g. the new original sentence checkbox on the user's sentences page).
But the negative effect of `ng-cloak` would be that the whole sidebar won't show up for a few seconds (similar to the delay of the search bar at the top). IMHO that would be acceptable and we probably need to work on the rather slow performance of the AngularJS code anyways.

**Comment by trang** [comment]
I wouldn't consider this design definitive but I think it's still an improvement compared to the very long menu that we currently have. I'll go ahead and merge this.

**Some notes**

My problem here is the same as with the "Compose" button during the [redesign of the private messages](https://tatoeba.org/eng/wall/show_message/33564#message_33564). It feels out of place to have something that looks like a button that is just floating around.

It would be visually more in line with our design patterns if the menu was showing a few items and had a "More" button to show the rest of the items and "Less" to hide them again (similar to the sentence component). But we would then have to decide which items should be displayed by default.

For deniko's issue, I also think it's okay to add ng-cloak on the sidebar.

**Comment by RyckRichards** [comment]
@AndiPersti - May I know your username on Tatoeba?

**Comment by AndiPersti** [comment]
https://tatoeba.org/eng/user/profile/rumpelstilzchen

**Pull request merged**
