### PR TITLE
Improve AngularJS performance a little bit

### PR DESCRIPTION
**Pull request by AndiPersti**
According to the [docs](https://docs.angularjs.org/guide/production) disabling debug info and comment and CSS class directives should improve the perfomance a little bit.

### CODE REVIEW

**Comment by jiru** [comment]
Shouldn’t AngularJS’s debug be activated when debug is enabled in app_local.php?

**Comment by AndiPersti** [comment]
You can always enable the debug info from the console using `angular.reloadWithDebugInfo()` so I don't think it's necessary that it is enabled by default even in a development environment.

**Comment by jiru** [comment]
I’m just afraid that we won’t see the stacktraces when something fails while loading the page.

**Comment by AndiPersti** [comment]
This change has no effect on stacktraces. See [Disabling Debug Data](https://code.angularjs.org/1.6.1/docs/guide/production#disabling-debug-data) for the things which will be disabled by this change.

**Comment by jiru** [comment]
Alright then! Thank you for answering my questions :slightly_smiling_face:

**Pull request merged**
