### PR TITLE
solves issue#958

### PR DESCRIPTION
**Pull request by achaitanyasai**
ping @ckjpn @trang 
solves issue #958 , added extra conditions for exclude flag.

### CODE REVIEW

**Comment by jiru** [comment]
Looks fine, thanks!

**Comment by jiru** [comment]
I had to fix a syntax error (missing comma). Please run your code before committing it!

**Comment by trang** [comment]
@achaitanyasai, I added an article in the wiki about submitting pull requests: 
https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-pull-requests
I hope it will help you for your future pull requests.

A few more things:
- You don't need to ping anyone in the pull request. We receive notifications whenever a pull request is submitted.
- ckjpn is not a developer, he wouldn't be able to review your pull request.
- Your commit message should contain more information than just a reference to the issue you've solved. Here for instance, you could have something like "Fix title for advanced search with exclude option".

**Comment by achaitanyasai** [comment]
Oh thanks a lot, I will follow the guidelines from now on.

**Pull request merged**
